### ISSUE TITLE
challenge participant progress page should not use grey for tasks

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10907]
_EDIT: There's a partial PR at https://github.com/HabitRPG/habitica/pull/10973 which a contributor could build on if they didn't want to work on this issue from scratch._

When you are looking at a challenge's page (e.g., a page such as `https://habitica.com/challenges/6c565677-65fc-400f-b39e-52bd01e4cd7a`) and you use the "View Progress Of" > "Select a Participant" menu to view the progress of a participant, completed Dailies and To-Dos should not be grey - they should show their red/orange/yellow/green/blue colour so that you can judge the participant's history of performing that task.

For example, in the screenshot below, the Daily should not be grey.
![image](https://user-images.githubusercontent.com/1495809/49847475-13d3ff00-fe1c-11e8-87d2-113242d08a16.png)

Whoever works on this issue should test that their change does not affect any tasks (including challenge tasks) in a player's own tasks list, or in the "Group Tasks List" screen of a guild or party with a Group Plan. For information about adding a Group Plan to a guild/party, see "Creating Test Data" in [Using Your Local Install to Modify Habitica's Website and API](https://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API)

**Comment by zmontgo** [comment]
I think I understand what you mean. So if I'm right, you are saying that when you view the person's status, their completed dailies should show the colour that it was when they checked it off? If not, please correct me. But I'd love to take this on!

**Comment by Mira-M** [comment]
I'd like take on this one please!

**Comment by Alys** [comment]
Thanks @Mira-M! I've changed the label to in progress.

**Comment by gautamz07** [comment]
@Alys i believe this has been fixed ? i was just checking this issue , locally and it seemed fine.

**Comment by Alys** [comment]
@gautamz07 Thanks for checking but it is still happening. You can see an example in https://habitica.com/challenges/3d599f05-8e14-4078-bf2c-718d6852edc4 when you look at the All tab for Dailies.

**Comment by Mira-M** [comment]
I put in a PR back then, and changes were requested, but at the time I lost my local changes due to my computer dying and haven’t had the chance to pick it back up. The branch is still there with the unit tests if someone wants to pick it up. Thanks.

**Comment by Alys** [comment]
@Mira-M Thanks for telling us! I'll mark this issue as help wanted again and the PR as "abandoned" but that's just the label we use when a PR is available to be taken up by someone else.

If you do want to work on it again or if you'd like advice about restoring your changes locally from what's in the PR, just let us know!

**Comment by gautamz07** [comment]
@Alys will take this up . Let me know :)

**Comment by Alys** [comment]
@gautamz07 Thank you! Please go ahead. :)

**Comment by gautamz07** [comment]
@Alys , Thank you . the challenge link that you shared [HERE](https://habitica.com/challenges/3d599f05-8e14-4078-bf2c-718d6852edc4 ) , i can see that the dailies of other users not always show in grey when inspected see [HERE](https://i.imgur.com/9y3eZ1p.jpg) , one is showing the progress correctly while one is in grey. Also i suppose this issue only happens in the ALL tab. I was unable to recreate this issue locally though , heres what i did.

- created two separate acounts locally.
- created a challenge from account A. Joined challenge
- joined challenge from account B.
- did not check/tick any of the dailies from A.
- Checked progress of A from account B.

Still none of the dailies show in grey. Could you give me a bit of insight into this. Iám a little new to habitica so sorry for the noob question.

Thank you.

**Comment by Alys** [comment]
Dailies are grey when they've been completed (i.e., when they have a tick mark in their checkbox) or when they're not due. If you use one of your test accounts to complete a challenge Daily and then look at that account's progress from the challenge's screen, you should see that Daily appearing grey with a tick in the checkbox. Also you can edit the Daily's repeat settings (in the challenge's screen, not in your own copy of the Daily) so that the Daily is not due today (e.g., change it to only Mondays or set the Start Date to a day in the future). You should then see that it becomes grey in the challenge's own page.

Does that make sense? Post here again if it's not clear enough or if you need more pointers!

**Comment by anishlukk123** [comment]
@SabreCat  is this issue still relavant, and if is not relavant can we close this issue , and if it is I would like to work on it

**Comment by ghost** [comment]
I propose another solution: make the completed tasks or dailies grey, but surrounded by the appropriate colour. I'm not a web developer, so I can't deal with this, but I'm aware that this is just a suggestion.

**Comment by Tressley** [comment]
Thanks for the suggestions. Removing the "Help Wanted" label from this issue so the Habitica team can discuss the best way to handle.
