### ISSUE TITLE
incorrect Pets (and maybe Mounts) displayed / starred in Stable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10997]
There's client-side bugs in the Stable related to searching for and equipping pets.

It might affect mounts too. I haven't tested since I assume that if mounts are broken too, the pets fix would fix them as well. However any coder working on this might want to test mounts either before their fix or at least afterwards.

Here's a report by Praxis  @Praxissima (0ce6d43b-efa2-45a3-acaa-59daad7d658d) and below that is the results of my testing:

> Shortly after I purchased the Rose Quartz hatching potions and created some matching pets and mounts, I noticed a new bug with the stable selection interface, when using the search function (which is much needed once the Stable reaches a significant population). Since it was behaving perfectly before, maybe there is a connection between the two.
> 
> To illustrate the problem, here's what happened when I tested again just now:
> 
> Typed "cupid" in the search bar, to bring up all possible Cupid type pets in the main Stable graphical menu.
> 
> Selected Cupid wolf cub: got Purple wolf cub in Avatar window.
> 
> Typed/selected Shimmer wolf cub: same result.
> 
> Typed/selected Fairy wolf cub: same result.
> 
> Then I went back to Cupid wolf cub, same result.
> 
> Then I tried to select Cupid panda cub: got FAIRY panda cub.
> 
> From that point, ALL the pet selections went to Fairy type instead of the kind that I typed and I selected (i.e. correct species, wrong color/type). Then I noticed something in the main Stable menu window (in addition to the wrong pet displaying in the Avatar window):
> 
> Comparing the avatar display with the graphical menu in the main stable window, The Fairy lion cub (which I may have purposely chosen) was displaying in the Avatar window, but BOTH the Purple lion cub AND the Fairy lion cub showed (with a "star" in the upper left corner) in the main Stable menu as the currently selected pets.
> 
> Earlier, I found that it won't always even display the right species. I started having problems when the Rose Quartz flying piglet seemed to set every subsequent selection to flying pig, regardless of the species of pet selected, only in the selected color/type (wrong pet, right color).
> 
> In other words, it seems somewhat random, but with SOME consistent patterns, and it all started shortly after the introduction of the Rose Quartz pets (at least that gives you a time frame to check on recent adjustments to the Stable code, in case it's not directly related to the Rose Quartz pets).
> 
> So far, it doesn't SEEM to be affecting the selection of mounts, but I can't be positive about that as I don't want to spend inordinate amounts of time testing every permutation. Hopefully I've given enough information here for your coders to test and trouble-shoot this now.
> 
> The only way to reliably get the exact pet I want (which is a hassle, as I now have so many and the main Stable window displays a LOT of entries) is to clear the search bar of text, expand the correct category of pet and manually choose it from the graphical menu of pets. With my limited testing, it seems to only go wrong when I pull up the category using text in the search bar, and THEN select a pet from the menu display in the main Stable window.

I haven't tried to replicate any of that exact behaviour but when I started some tests on my own account I quickly found problems:
1. I entered "cupid" in the search box (worked correctly).
2. I equipped a Cupid Panda (worked correctly).
3. I enterd "rose" in the search box (worked correctly - I saw the empty pawprints for the Rose Quartz pets.
4. I hatched the first two pets (worked correctly).
5. I scrolled down to see the next pawprint (the Rose Quartz panda) and then noticed that it was already starred as if I had it equipped, but I still had the Cupid Panda equipped. See the first screenshot below. At that time, this was in my User document:
```
{
    "_id": "d904bd62-da08-416b-a816-ba797c9ee265",
    "items": {
        "currentMount": "TigerCub-Spooky",
        "currentPet": "PandaCub-Cupid"
    },
}
```
6. I reloaded and searched for "rose" (worked correctly - the Rose Quartz Panda was no longer starred).
7. I searched for "cupid". The Cupid pets were shown but the Cupid Panda was not starred. See the second screenshot below. I checked my User document again and it was still the same as above - i.e., the Cupid Panda should have been starred.

![image](https://user-images.githubusercontent.com/1495809/52908192-61596600-32bc-11e9-8391-a445974dd465.png)

![image](https://user-images.githubusercontent.com/1495809/52908259-a8942680-32bd-11e9-852f-303a222fc26e.png)

**Comment by Alys** [comment]
Extra info from Praxis @Praxissima (0ce6d43b-efa2-45a3-acaa-59daad7d658d) (everything below is their post from RaB):

I think it may help to add that the selection process when it (nearly always) went wrong involved these steps:

1. Type a "type" keyword (such as quartz) in the search bar.
1. Select a specific pet species (e.g.fox) from the menu of pet icons that display in the main window.

Today I noticed that if I type in BOTH the pet color/type (e.g. "quartz") AND the pet species (e.g. "fox") in the search bar, which narrows it down to exactly one possible pet and mount (e.g. "quartz fox") it seems to work properly.

So maybe the problem doesn't kick in unless you are selecting from a set of possible species choices (icons of different species of that particular type) in the main Stable window.

My usual M.O. is to type in a pet "type" keyword (e.g. Quartz, Shimmer, etc.) and then look over the selection of various species of that type, and maybe try a few to see how they look with my current outfit and background. That method is the one that produced the most consistently wonky results over the past few days.

**Comment by shanaqui** [comment]
Extra info:

> UPDATE ON THE STABLE SEARCH ISSUES BUG:
> 
> Yesterday I reported that the search selection appeared to work when I typed in BOTH the pet type/color AND species in the search bar...
> 
> Then again, nope! Just now I typed "snow panda" into the search box, and it correctly displayed the "Icy Snow" panda pet and mount icons in the main Stable menu.
> 
> I selected the Icy Show panda cub... and got the Purple wolf cub. And, now that I think of it, when I first noticed the search selection problem, it was selecting and displaying the Purple wolf cub pretty much every time, no matter what color or species of pet was typed in or selected.
> 
> So that's another piece of info for your coders... apparently typing in the specific type and species of pet in the search bar does NOT guarantee a correct selection. I must have just been lucky yesterday when that was working.
> 
> I hope you'll add this to @Alys 's GitHub issue, and that the added info helps your coders to fix the Stable search selection issues. Thanks again for all your help!

**Comment by shanaqui** [comment]
Here's a further report from Praxis:

> FURTHER UPDATE ON THE STABLE SELECTION BUG:
> 
> @shanaqui Thanks for updating the info for the coders. Now it seems that the problem is more extensive than what I reported: I've just discovered that the problem is NOT limited to pets selected after typing in search terms.
> 
> Without entering any search terms, I picked an Icy Snow wolf cub from the lineup of icons... and got the Starry Night wolf cub instead. I chose a different wolf color, and got a Purple wolf cub (instead of my selection) that time.
> 
> Deciding to try the search once again (this time just for species) I typed in "owl" and chose the blue owl... that worked... then clicked on the base color owl... and got the base color GRYPHON instead.
> 
> So, basically, it's inconsistently wonky, whether or not you use the search function, and the errors can include species errors as well as color errors. Here's hoping this newest info will be added to the growing pile of information, and that it will help our mighty coders to fix the problem.
> 
> Thanks again!

*However*, I cannot reproduce this or indeed any of the issues they were seeing.

I can reproduce what Alys saw.

**Comment by alecbrick** [comment]
I was able to reproduce what Alys saw, as well as Praxis' description from Alys' second post. I can't tell you exactly what the issue was, since I don't know Vue well enough to tell, but I think I was able to fix it. However, I wasn't able to reproduce the behavior in the original post, or in the most recent post.

**Comment by paglias** [comment]
Merged a fix from @alecbrick I'm not going to close the issue as it's possible not everything has been fixed but we'll see once it goes live next week

**Comment by SabreCat** [comment]
I definitely still see sync issues here, where I'll hatch a pet and equip it but nothing will visibly happen, requiring extra sync or reload.

**Comment by alecbrick** [comment]
@SabreCat I've just looked into this a bit. I'm seeing a few sync issues as well, but I'm unable to reliably reproduce them.

**Comment by alecbrick** [comment]
So this isn't related to the original issue, but I found that the *first time* you buy anything from the store, it doesn't automatically sync. I'll look into this more, but my guess is that it's due to the fact that the objects returned by a call to `buyOp()` only list items you've bought before. If you've bought something but no longer own it, it says you have 0 of that item, whereas if you've never owned an item, it doesn't show up in the item object. It's possible that this issue is related to the issue described on this page.

**Comment by paglias** [comment]
@alecbrick what type of items are you talking about that don't appear?

There was a similar issue that I thought we had fixed that caused items you never owned to don't show up immediately due to how Vue's reactivity works. Here you can see how new keys are added to objects to ensure they show up right away https://github.com/HabitRPG/habitica/blob/develop/website/common/script/ops/buy/purchase.js#L49-L52


And I'm seeing maybe we skipped one instance here https://github.com/HabitRPG/habitica/blob/develop/website/common/script/ops/buy/purchase.js#L56-L68?

But yeah if you could specify the type of item that would be very useful

**Comment by alecbrick** [comment]
I've verified that this occurs for food, and I'm pretty sure it happens for eggs and potions as well.

**Comment by Alys** [comment]
@alecbrick Would you like to create a new issue for it and copy your comments from here to that? That would be helpful for us! If you'd rather not, that's fine and i will later. If you do want to, you'll see that the new issue template tells you to post to the Report a Bug guild - just ignore that for this case. :)

**Comment by alecbrick** [comment]
Sure, I can do that.

**Comment by Alys** [comment]
I've tidied up this issue by deleting some posts that weren't related and were later logged in issue 11907 (now resolved).

I'm not sure if this issue is still happening. I can't reproduce it in a few tests just now but it sounds like it was intermittent so reproducing it reliably may not be possible.

**Comment by veeeeeee** [comment]
Closing as we haven't come across any recent examples of this specific issue. Can reopen if one comes up, or start a new issue if it's a variation on this ticket.
