### ISSUE TITLE
can't buy facial hair (and maybe other avatar customisations)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11096]
My account has two facial hairs available for purchase (screenshot below). When I click on the gem icons, nothing happens (literally nothing).

No console messages appear. 

![image](https://user-images.githubusercontent.com/1495809/55383737-3d03d100-556c-11e9-90a0-0ffed2772b6f.png)

**Comment by paglias** [comment]
The loggly error has been fixed but it's unrelated

**Comment by Alys** [comment]
This is still happening. I've edited the top post to remove the part about Loggly messages since it wasn't related.
It will almost certanly be a front-end vue error so I've marked this as medium level coding.

**Comment by Alys** [comment]
It will almost certanly be a front-end vue error so I've marked this as medium level coding.

**Comment by Scens** [comment]
I've created a pull request that fixes the issue. The issue wasn't only clicking on the gem icon, but anywhere in the lower part of the option's square.
