### ISSUE TITLE
casting Healing Light skill at full HP gives "language is undefined" error

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12839]
When a Healer has full health (50 HP) and tries to use the Healing Light skill (`heal`), they see an error message saying either `Cannot read property 'language' of undefined` or `a is undefined`. (Which error you get may be browser dependent.)

The expected behaviour is that they should see the `messageHealthAlreadyMax` message ("You already have maximum health.")

The skill works correctly when health is not already full.

This is probably the code responsible:
https://github.com/HabitRPG/habitica/blob/8ac48406e91f39a475f41bd11bfe01dab98aebe3/website/common/script/content/spells.js#L233 

I expect that `req.language` isn't defined at the time that the code is being run in a browser but I haven't done anything to try to confirm that so don't take my word for it. :)

---

_Thanks to @johnjsal (624e48a3-cbea-4bbe-ae44-ca9183f49626) for reporting this!_

**Comment by paglias** [comment]
Was a one line fix so I pushed it

**Comment by JohnJSal** [comment]
Hi. I was the one who reported the issue. I just wanted to mention that I still receive the same error. I've tried refreshing and restarting Chrome. Is there anything else that I might need to do to "force" the fix?

Here's an image of the error pop-up: https://snipboard.io/qTZuxr.jpg

**Comment by thewilloftheshadow** [comment]
@JohnJSal it won't be actually fixed on the live version until they merge the develop branch into the actual website, which happens every 3 days to a week from what I've seen

**Comment by JohnJSal** [comment]
Ah, of course! Thank you!
