### ISSUE TITLE
quest box not appearing on party page for players using certain languages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13255]
We've had several reports of people who are participating in quests not being able to see the quest details on their party page.
I haven't worked out why but I'm seeking more information from the people who've reported it.
Below are the reports we've seen so far in the Report a Bug guild.

---

@-Tyr- (38009d36-5a27-4ef0-a890-e81f4c847425) one to two days ago (this is the first report):

> I currently have no quest display in my party sidebar. We are currently on a quest, but there is no quest boss image, health bar etc.. All there is is the party description and challenges.
>
> ... screenshot of the missing quest details in the party sidebar. [see below for the screenshot]
> This is Chrome web browser on a Windows computer.
>
> Another member of my party (who is also using Chrome on a Windows computer) can see the quest details. We are currently on a quest.

@Transurfer (ffe1c057-537c-454d-873f-c590b162ff2c):

> Something has happened to my party today. We are on the quest but you can't see it on the website. The whole part for the quest is missing.
>
> I've checked the app and the quest is there. On the website still nothing. There is the whole part for the quest missing. It shows Description and Challenges and that's it between Invite and Leave party buttons.

@fernandojtx (a5a8c688-eb0f-40d4-b4ff-b05c99595fa6):

> me and my group were on a quest and it simply disappeared 

@Zelah_Meyer (8ea14435-ab6e-4185-86ac-3d663bf616ba):

> Can confirm that I am also suffering from the quest vanishing on the PC version (I'm in Chrome). It happened yesterday and I had to guess how much damage needed doing to complete the quest. Succeeded in defeating the monster when I logged in this morning (even though it was hidden yesterday). My friend sent out an invite for a new quest today and I could see that but when I got the e-mail to say she'd started the quest, I checked the site and it had vanished again. I can see the monster & my damage on the app, but there's nothing on PC.

@Prairiehamster (a6ca1bdf-510d-4730-b471-4d2a4e3fe719):

> I'm also having an issue with the disappearing quest - Windows 10 PC, using up to date Chrome. I've confirmed we're still fighting the boss - I just did damage to it a few minutes ago and I can see it on my app. But on the pc, nothing.

-----

So far all the reports have either not given platform information or have said that they're on Chrome on Windows. But @-Tyr- has said that a party member who is also using Chrome on Windows CAN see the quest, so it's not necessarily a Chrome problem. This report also means it's not a problem with a specific quest or a specific party.

I can see my party's quest (`atom3`) on Firefox on Ubuntu. I can still see it when I change the quest to be `ghost_stag`, which is the quest that one of the affected players is on.

I've done some comparison of party and quest data between all the reports and can't see anything in common.

I'm asking for console log messages and testing on other browsers.

---

Here's -Tyr-'s screenshot:

![image](https://user-images.githubusercontent.com/1495809/117533782-02fe3680-b032-11eb-993e-26eea9dfd8ce.png)

**Comment by 95VictorVictor2** [comment]
Hi, this is -Tyr-. I have the JS Console errors:
```
logging.js:30 Unhandled error in Vue.js code.
n.default.config.errorHandler @ logging.js:30
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:31 Error: RangeError: Incorrect locale information provided
    at Number.toLocaleString (<anonymous>)
    at Bh (localizeNumber.js:13)
    at a.ft (questSidebarSection.vue?c281:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at new nr (vue.runtime.esm.js:4468)
    at $n (vue.runtime.esm.js:4073)
    at a.xr.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
n.default.config.errorHandler @ logging.js:31
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:32 Component where it occurred: a {_uid: 1043, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$attrs: (...)$children: []$createElement: ƒ (e,n,r,i)$el: comment$listeners: (...)$options: {parent: a, _parentVnode: yt, propsData: {…}, _parentListeners: undefined, _renderChildren: undefined, …}$parent: a {_uid: 157, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$refs: {}$root: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}$scopedSlots: {$stable: true, $key: undefined, $hasNormal: false}$slots: {}$store: e {_actions: {…}, getters: {…}, _vm: xr}$vnode: yt {tag: "vue-component-300-quest-sidebar-section", data: {…}, children: undefined, text: undefined, elm: comment, …}acceptedCount: (...)bossHpPercent: (...)canEditQuest: (...)group: (...)icons: (...)isMemberOfPendingQuest: (...)isMemberOfRunningQuest: (...)onActiveQuest: (...)onPendingQuest: (...)openParticipantList: ƒ ()openQuestDetails: ƒ ()openStartQuestModal: ƒ ()questAbort: ƒ ()questAccept: ƒ ()questData: (...)questLeave: ƒ ()questReject: ƒ ()user: (...)userIsOnQuest: (...)_bv__modal: t {_vm: a, _root: xr}_bv__toast: t {_vm: a, _root: xr}_c: ƒ (e,n,r,i)_computedWatchers: {user: nr, userIsOnQuest: nr, onPendingQuest: nr, onActiveQuest: nr, bossHpPercent: nr, …}_data: {__ob__: Et}_directInactive: false_events: {}_hasHookEvent: false_inactive: null_isBeingDestroyed: false_isDestroyed: false_isMounted: true_isVue: true_props: {}_renderProxy: a {_uid: 1043, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_routerRoot: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}_self: a {_uid: 1043, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_staticTrees: (5) [empty × 3, yt, yt]_uid: 1043_vnode: yt {tag: undefined, data: undefined, children: undefined, text: "", elm: comment, …}_watcher: nr {vm: a, deep: false, user: false, lazy: false, sync: false, …}_watchers: (11) [nr, nr, nr, nr, nr, nr, nr, nr, nr, nr, nr]$bvModal: (...)$bvToast: (...)$data: (...)$isServer: (...)$props: (...)$route: (...)$router: (...)$ssrContext: (...)get $attrs: ƒ ()set $attrs: ƒ (e)get $listeners: ƒ ()set $listeners: ƒ (e)get icons: ƒ ()set icons: ƒ (t)__proto__: xr
n.default.config.errorHandler @ logging.js:32
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:33 Info: render
```

**Comment by Basrara** [comment]
i also get js console errors, on firefox, chrome, and edge (all windows 10). i'm @dicedweller on habitica.

### Firefox:

Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. party
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 8
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. analyser.js:485:17
Feature Policy: Unbekannte Funktionalität (Feature) "payment" wird ignoriert. v3:1:38621
Feature Policy: Unbekannte Funktionalität (Feature) "payment" wird ignoriert. v3:1:38713
Unhandled error in Vue.js code. logging.js:30:12
    errorHandler logging.js:30
    VueJS 32
    e group.vue:592
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    s Babel
    (Async: promise callback)
    r chunk-vendors.6a592fd7.js:94
    Babel 3
    fetchGuild group.vue:585
    e group.vue:502
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    Babel 3
    mounted group.vue:499
    VueJS 18
    created app.vue:400
    (Async: promise callback)
    created app.vue:399
    VueJS 17
    56d7 main.js:36
    Webpack 6
Error: RangeError: invalid language tag: "en_GB"
    Bh localizeNumber.js:13
    ft questSidebarSection.vue:1
    VueJS 30
    e group.vue:592
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    s Babel
    promise callback*r chunk-vendors.6a592fd7.js:94
    Babel 3
    fetchGuild group.vue:585
    e group.vue:502
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    Babel 3
    mounted group.vue:499
    VueJS 18
    created app.vue:400
    promise callback*created app.vue:399
    VueJS 17
    56d7 main.js:36
    Webpack 6
logging.js:31:12
    errorHandler logging.js:31
    VueJS 32
    e group.vue:592
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    s Babel
    (Async: promise callback)
    r chunk-vendors.6a592fd7.js:94
    Babel 3
    fetchGuild group.vue:585
    e group.vue:502
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    Babel 3
    mounted group.vue:499
    VueJS 18
    created app.vue:400
    (Async: promise callback)
    created app.vue:399
    VueJS 17
    56d7 main.js:36
    Webpack 6
Component where it occurred: 
Object { _uid: 1018, _isVue: true, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": [], "$refs": {}, _watcher: {…}, … }
logging.js:32:12
    errorHandler logging.js:32
    VueJS 32
    e group.vue:592
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    s Babel
    (Async: promise callback)
    r chunk-vendors.6a592fd7.js:94
    Babel 3
    fetchGuild group.vue:585
    e group.vue:502
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    Babel 3
    mounted group.vue:499
    VueJS 18
    created app.vue:400
    (Async: promise callback)
    created app.vue:399
    VueJS 17
    56d7 main.js:36
    Webpack 6
Info: render logging.js:33:12
    errorHandler logging.js:33
    VueJS 32
    e group.vue:592
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    s Babel
    (Async: promise callback)
    r chunk-vendors.6a592fd7.js:94
    Babel 3
    fetchGuild group.vue:585
    e group.vue:502
    u runtime.js:45
    k runtime.js:271
    e runtime.js:97
    r Lodash
    Babel 3
    mounted group.vue:499
    VueJS 18
    created app.vue:400
    (Async: promise callback)
    created app.vue:399
    VueJS 17
    56d7 main.js:36
    Webpack 6
Feature Policy: Unbekannte Funktionalität (Feature) "payment" wird ignoriert. v3:1:37908
Error: Could not establish connection. Receiving end does not exist. mcafee_wa_content.js:23:63330
Error: Could not establish connection. Receiving end does not exist. mcafee_wa_content.js:23:12894
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://f9b7afce-c0fa-43a6-b6e9-34ed15868513/mcafee_wa_content.js
Source-Map-Adresse: ../sourceMap/firefox/mcafee_wa_content.map

​

### Chrome (with dark mode extension):

Unhandled error in Vue.js code.
n.default.config.errorHandler @ logging.js:30
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:31 Error: RangeError: Incorrect locale information provided
    at Number.toLocaleString (<anonymous>)
    at Bh (localizeNumber.js:13)
    at a.ft (questSidebarSection.vue?c281:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at new nr (vue.runtime.esm.js:4468)
    at $n (vue.runtime.esm.js:4073)
    at a.xr.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
n.default.config.errorHandler @ logging.js:31
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:32 Component where it occurred: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$attrs: (...)$children: []$createElement: ƒ (e,n,r,i)$el: comment$listeners: (...)$options: {parent: a, _parentVnode: yt, propsData: {…}, _parentListeners: undefined, _renderChildren: undefined, …}$parent: a {_uid: 156, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$refs: {}$root: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}$scopedSlots: {$stable: true, $key: undefined, $hasNormal: false}$slots: {}$store: e {_actions: {…}, getters: {…}, _vm: xr}$vnode: yt {tag: "vue-component-300-quest-sidebar-section", data: {…}, children: undefined, text: undefined, elm: comment, …}acceptedCount: (...)bossHpPercent: (...)canEditQuest: (...)group: (...)icons: (...)isMemberOfPendingQuest: (...)isMemberOfRunningQuest: (...)onActiveQuest: (...)onPendingQuest: (...)openParticipantList: ƒ ()openQuestDetails: ƒ ()openStartQuestModal: ƒ ()questAbort: ƒ ()questAccept: ƒ ()questData: (...)questLeave: ƒ ()questReject: ƒ ()user: (...)userIsOnQuest: (...)_bv__modal: t {_vm: a, _root: xr}_bv__toast: t {_vm: a, _root: xr}_c: ƒ (e,n,r,i)_computedWatchers: {user: nr, userIsOnQuest: nr, onPendingQuest: nr, onActiveQuest: nr, bossHpPercent: nr, …}_data: {__ob__: Et}_directInactive: false_events: {}_hasHookEvent: false_inactive: null_isBeingDestroyed: false_isDestroyed: false_isMounted: true_isVue: true_props: {}_renderProxy: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_routerRoot: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}_self: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_staticTrees: (5) [empty × 3, yt, yt]_uid: 1018_vnode: yt {tag: undefined, data: undefined, children: undefined, text: "", elm: comment, …}_watcher: nr {vm: a, deep: false, user: false, lazy: false, sync: false, …}_watchers: (11) [nr, nr, nr, nr, nr, nr, nr, nr, nr, nr, nr]$bvModal: (...)$bvToast: (...)$data: (...)$isServer: (...)$props: (...)$route: (...)$router: (...)$ssrContext: (...)get $attrs: ƒ ()set $attrs: ƒ (e)get $listeners: ƒ ()set $listeners: ƒ (e)get icons: ƒ ()set icons: ƒ (t)__proto__: xr
n.default.config.errorHandler @ logging.js:32
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonymous) @ group.vue:592
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonymous) @ group.vue:502
u @ runtime.js:45
(anonymous) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (async)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ app.vue:400
Promise.then (async)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonymous) @ bootstrap:267
(anonymous) @ app.35ff403e.js:1
logging.js:33 Info: render



### Edge:

Unhandled error in Vue.js code.
n.default.config.errorHandler @ logging.js:30
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonym) @ group.vue:592
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (asynchron)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonym) @ group.vue:502
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonym) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonym) @ app.vue:400
Promise.then (asynchron)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonym) @ bootstrap:267
(anonym) @ app.35ff403e.js:1
logging.js:31 Error: RangeError: Incorrect locale information provided
    at Number.toLocaleString (<anonymous>)
    at Bh (localizeNumber.js:13)
    at a.ft (questSidebarSection.vue?c281:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at new nr (vue.runtime.esm.js:4468)
    at $n (vue.runtime.esm.js:4073)
    at a.xr.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
n.default.config.errorHandler @ logging.js:31
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonym) @ group.vue:592
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (asynchron)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonym) @ group.vue:502
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonym) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonym) @ app.vue:400
Promise.then (asynchron)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonym) @ bootstrap:267
(anonym) @ app.35ff403e.js:1
logging.js:32 Component where it occurred: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$attrs: (...)$children: []$createElement: ƒ (e,n,r,i)$el: comment$listeners: (...)$options: {parent: a, _parentVnode: yt, propsData: {…}, _parentListeners: undefined, _renderChildren: undefined, …}$parent: a {_uid: 156, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}$refs: {}$root: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}$scopedSlots: {$stable: true, $key: undefined, $hasNormal: false}$slots: {}$store: e {_actions: {…}, getters: {…}, _vm: xr}$vnode: yt {tag: "vue-component-300-quest-sidebar-section", data: {…}, children: undefined, text: undefined, elm: comment, …}acceptedCount: (...)bossHpPercent: (...)canEditQuest: (...)group: (...)icons: (...)isMemberOfPendingQuest: (...)isMemberOfRunningQuest: (...)onActiveQuest: (...)onPendingQuest: (...)openParticipantList: ƒ ()openQuestDetails: ƒ ()openStartQuestModal: ƒ ()questAbort: ƒ ()questAccept: ƒ ()questData: (...)questLeave: ƒ ()questReject: ƒ ()user: (...)userIsOnQuest: (...)_bv__modal: t {_vm: a, _root: xr}_bv__toast: t {_vm: a, _root: xr}_c: ƒ (e,n,r,i)_computedWatchers: {user: nr, userIsOnQuest: nr, onPendingQuest: nr, onActiveQuest: nr, bossHpPercent: nr, …}_data: {__ob__: Et}_directInactive: false_events: {}_hasHookEvent: false_inactive: null_isBeingDestroyed: false_isDestroyed: false_isMounted: true_isVue: true_props: {}_renderProxy: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_routerRoot: xr {_uid: 3, _isVue: true, $options: {…}, _renderProxy: xr, _self: xr, …}_self: a {_uid: 1018, _isVue: true, $options: {…}, _renderProxy: a, _self: a, …}_staticTrees: (5) [leer x 3, yt, yt]_uid: 1018_vnode: yt {tag: undefined, data: undefined, children: undefined, text: "", elm: comment, …}_watcher: nr {vm: a, deep: false, user: false, lazy: false, sync: false, …}_watchers: (11) [nr, nr, nr, nr, nr, nr, nr, nr, nr, nr, nr]$bvModal: (...)$bvToast: (...)$data: (...)$isServer: (...)$props: (...)$route: (...)$router: (...)$ssrContext: (...)get $attrs: ƒ ()set $attrs: ƒ (e)get $listeners: ƒ ()set $listeners: ƒ (e)get icons: ƒ ()set icons: ƒ (t)__proto__: xr
n.default.config.errorHandler @ logging.js:32
re @ vue.runtime.esm.js:1870
ee @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
y @ vue.runtime.esm.js:6053
h @ vue.runtime.esm.js:5954
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
rr.set @ vue.runtime.esm.js:4631
(anonym) @ group.vue:592
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (asynchron)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
fetchGuild @ group.vue:585
(anonym) @ group.vue:502
u @ runtime.js:45
(anonym) @ runtime.js:271
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonym) @ asyncToGenerator.js:32
(anonym) @ asyncToGenerator.js:21
mounted @ group.vue:499
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
E @ vue.runtime.esm.js:6346
(anonym) @ vue.runtime.esm.js:6565
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr.run @ vue.runtime.esm.js:4554
Zn @ vue.runtime.esm.js:4310
(anonym) @ vue.runtime.esm.js:1980
ue @ vue.runtime.esm.js:1906
Promise.then (asynchron)
oe @ vue.runtime.esm.js:1933
pe @ vue.runtime.esm.js:1990
tr @ vue.runtime.esm.js:4402
nr.update @ vue.runtime.esm.js:4544
mt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonym) @ app.vue:400
Promise.then (asynchron)
created @ app.vue:399
ne @ vue.runtime.esm.js:1854
Ln @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
on @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
p @ vue.runtime.esm.js:5978
h @ vue.runtime.esm.js:5925
(anonym) @ vue.runtime.esm.js:6516
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
nr.get @ vue.runtime.esm.js:4479
nr @ vue.runtime.esm.js:4468
$n @ vue.runtime.esm.js:4073
xr.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
xr @ vue.runtime.esm.js:5085
56d7 @ main.js:36
c @ bootstrap:89
0 @ app.35ff403e.js:1
c @ bootstrap:89
a @ bootstrap:45
(anonym) @ bootstrap:267
(anonym) @ app.35ff403e.js:1
logging.js:33

**Comment by Alys** [comment]
In addition to the two posts above, -Tyr- (@95VictorVictor2) and dicedweller (@Basrara) have given the following helpful information:

@-Tyr-:
> I have been able to reproduce this on Microsoft Edge: same thing, I don't have quest info in that browser either. Also, I have added the JS console errors as a comment in GitHub. My party mate who can see the quest sidebar tells me that they do not have errors in the JS console.

@dicedweller:
> this also happens for me, in 3 different browsers on windows 10: firefox, chrome, and edge. i have a darkmode extension on chrome, but that doesn't seem to affect this bug. just posting here because i already uploaded the console texts (for all 3) on github.
> 
> (i will add that the bug also occurs on windows 7 [which noone should use anymore, i know], both on chrome and firefox (didn't check internet explorer there), if that's of any use.)

So it's clearly not related to the browser!

**Comment by Alys** [comment]
Heh. Solved it. :) Or at least part of it.

Both -Tyr- and dicedweller have their language set to en_GB, and so does one of the other affected players. Another one uses pt_BR, and the remaining players have `null` as their value for `preferences.language` . When I set mine to each of those three values, I can no longer see my party's quest. When I set it back to en or to fr (as a random choice of other languages), I see the quest.

I also can't see the quest box when I use any of these languages:
- hi_IN , tl_PH , nb_NO , ku_IQ ,  ur_PK , zh_HK , zh_Hant_HK , zh_TW

I CAN see it with:
- zh , tl , hi, and fr as mentioned above.
I got bored with testing after that. :)

So I'm wondering if something in the quest box's new code can't handle underscores in the language identifier. That doesn't explain `null` not working of course, but obviously `null` could easily be causing its own problems (and ideally it would never appear in `preferences.language`.

@negue Since you've worked on the code recently, do you have any ideas about what in the code might not be able to handle those languages?

EDIT: 
It might also be the length of the language abbreviation rather than the underscore. You could test with Pirate English, which is long but has no underscore.

**Comment by Alys** [comment]
It might also be the length of the language abbreviation rather than the underscore. You could test with Pirate English, which is long but has no underscore.

**Comment by citrusella** [comment]
Could the fact that pirate English has an @ (en@pirate) play into it? ...This is completely speculation but it occurred to me when you said Pirate English.

(...Now I wonder if en@lolcat would cause the issue but it's not actually available on the website yet. XD)

**Comment by citrusella** [comment]
Judging by:

```
Error: RangeError: invalid language tag: "en@pirate"
    Bh localizeNumber.js:13
    ft questSidebarSection.vue:1
```

(Which seems to be the most related error...) Is it correct to assume this could be an interaction of certain languages with the recent fix that allows decimal point localization? localizeNumber was created in #13178 and line 13 includes a toLocaleString method.

https://github.com/HabitRPG/habitica/blob/4dc718fbffc9e593309f48121a5d241ca87be240/website/client/src/filters/localizeNumber.js#L13

I don't know very *much* about toLocaleString but what I can find suggests it might have a set of "legal" values that might not include underscores but might take a few languages that have hyphens without issue (i.e. it might understand pt-BR but not pt_BR), might explain pirate and null to some extent too if it's expecting valid language tag and those aren't ones?

**Comment by negue** [comment]
@citrusella is right 🎉  - the issue is that `val.toLocaleString` only accepts dashed values => see https://www.w3schools.com/jsref/jsref_tolocalestring_number.asp

So in our function (`localizeNumber`) most of our `_` ones can be replaced by the dashed versions - the `en@` will have to use `en` there but all others might need to be used with `en` as fallback

**Comment by Helcostr** [comment]
I can tackle this issue. I wrote localized Number, and I can fix it. I didn't realize we had custom languages using the `@` symbol (no one officially uses it that way). Fix PR incoming.

**Comment by Alys** [comment]
@Helcostr I've marked this as in progress for you. Thanks for taking it on! 

Note that the languages with the @ symbol aren't the important ones - they're just en@pirate and en@lolcat (although if you can get them working with the quest box, that would be nice; otherwise just fall back to `en` for them).  The languages with the underscores are the critical ones to fix since they are real languages. Ideally it would need to be fixed in a way that doesn't require the dashed versions to be used throughout the site, since that would require a migration for all user data, and probably changes in Weblate, and may be a breaking change for the API.

**Comment by citrusella** [comment]
> I didn't realize we had custom languages using the `@` symbol (no one officially uses it that way)

I tried snooping around to see if this was maybe an established way to deal with this in Weblate and couldn't find anything there but *did* find evidence that the two English "sub-languages" Habitica has using @ (Pirate, which is currently usable, and LOLcat, which is not) are ["officially" notated with an @ in their support on Transifex](https://www.transifex.com/explore/languages/) (which is what Habitica used for translation collaboration before switching to Weblate). Maybe an artifact from that? (Transifex has other languages Habitica isn't using with the @, for reasons I couldn't fully ascertain...)

...And literally mere seconds before I hit "send" Alys shows up with more useful information. XD ~~\*sends post anyway*~~

**Comment by Helcostr** [comment]
```javascript
  return val.toLocaleString(
    // Catch null just incase
    (lang || '')
      // Strip beyond @ symbol to allow custom languages
      .replace(/@(?:.+)$/, '')
      // We use underscore, this mthd uses dash
      .replace('_', '-'),
    optOut);
```
literally already was executing haha. very simple fix. (and leaving comments just incase someone is confused)

I am just checking my lint and stuff, and contemplating if I want to use a try-catch to catch any issues with the `toLocalString` 🤔 (nvm, I decided against try-catch).

If we support non-en custom languages, I will catch the official code before the `@` symbol.

**Comment by shanaqui** [comment]
I'm reopening this since I suspect the fix for this issue is at fault for the new one: now, no matter what language I've tested, no quest details are visible for me on production or on delta.

**Comment by Helcostr** [comment]
Double checking to see if my fixes affected it. It shouldn't have 🤔

**Comment by SabreCat** [comment]
@Helcostr It is causing it, yeah, `optIn is undefined` being the exact error. Working on it here!

**Comment by Helcostr** [comment]
Oh god damit XD

```javascript
export default function localizeNumber (valIn, lang, optIn = {}) {
  // Extra catch just incase non number
  const val = (typeof valIn === 'number') ? valIn : parseFloat(valIn);

  // Options Management
  const { toFixed } = optIn;
  const optOut = {};
  if (typeof toFixed !== 'undefined') {
    optOut.maximumFractionDigits = toFixed;
    optOut.minimumFractionDigits = toFixed;
  }

  return val.toLocaleString(
    // Catch null just incase
    (lang || [])
      // Strip beyond @ symbol to allow custom languages
      .replace(/@(?:.+)$/, '')
      // We use underscore, this mthd uses dash
      .replace('_', '-'),
    optOut,
  );
}
```

I am thinking of adding this, but I forgot how default values work XD.

**Comment by SabreCat** [comment]
ha, yup, figured that out simultaneously with you! Fix headed up.

**Comment by Helcostr** [comment]
(My suggested change was because you told me optIn was undefined, i hope it works w/ linting)

All the catches i wrote, and i forgot the most critical one XD.

**Comment by SabreCat** [comment]
Eh, I made a silly mistake in the process as well, in that during my functional test I didn't have the correct kind of quest active... 🤦

**Comment by Helcostr** [comment]
Plz tell me that the fix is in place, I'm anxious D: 😅

**Comment by SabreCat** [comment]
It'll be live within ~5 minutes

**Comment by citrusella** [comment]
If I might ask a question: Would there be any reason a person *wouldn't* have been having the error across all languages after the original fix got pushed to delta and before the more recent one did? Asking because I played around in what should have been affected languages for the original issue on delta as soon as I could ascertain that the original fix was up on there and I didn't have any issues (on my currently-active boss quest with no rage bar) and assumed "oh cool, issue fixed"... but it sounds like I should have been completely unable to see it instead?

**Comment by Helcostr** [comment]
It's because when I fixed the rage boss, I intentionally didn't pass in an option object, thinking I had caught it.

Apparently I didn't XD

**Comment by SabreCat** [comment]
@citrusella The issue only affected bosses with Rage bars. That's the mistake I made when testing too!

**Comment by SabreCat** [comment]
Still not 100% fixed! See [this paste](https://pastebin.com/Amnuyr7e) for the error some users are running into...

**Comment by Alys** [comment]
This is the `null` case I mentioned here a couple of weeks ago. If you set your `preferences.language` to `null` or if you delete the `preferences.language` attribute, then the quest box can't be seen.

@shanaqui found three players who couldn't see the quest box and all of them had no `preferences.language` attribute.

For cases like that, one possible fix would be to cause the code to behave as if the player's language is `en`

**Comment by Helcostr** [comment]
```
null || []
```
this should be a valid solution 🤔 not sure what's going on... it evaluates to an empty array...

oh i see, it's not because null is a bad value to pass (cuz i caught it). it's because I'm passing an array and was also using str obj's replace function (on an array).
