### ISSUE TITLE
t.response undefined error when purchasing orb of rebirth

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#13973]
> A new bug report from @kalarime
> 
> I have tried to purchase the Orb of Rebirth and keep getting a "t.response undefined" error, then the page refreshes. Lather, rinse, repeat, over the past few days and despite refreshing the page several times. Not sure what's going on, send help!
> 
> UUID 	71fecd9f-5121-4cbd-86d3-c02ae20b683b
> User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
> Level 	105
> Class 	wizard
> Dailies Paused 	false
> Costume 	true
> Custom Day Start 	0
> Timezone Offset 	420

**Comment by vanathi-g** [comment]
Hey, this is similar to an issue I worked on with Keys to the Kennels. May I work on this one as well?

**Comment by CuriousMagpie** [comment]
Absolutely! Assigning you.

**Comment by CuriousMagpie** [comment]
Hey @vanathi-g, are you making any progress on this?

**Comment by vanathi-g** [comment]
Hey! Sorry, was busy with some other stuff. I was actually having trouble reproducing the issue when I checked last.

**Comment by CuriousMagpie** [comment]
Weird! Are you still having problems replicating the issue?

**Comment by saraolson** [comment]
im also having trouble replicating the issue now, and i had gotten it before. 

now though, the orb just won't work on my first use. i see it available for 0 gems, i get the modal, i click buy, the page refreshes, but im still a level 112 rogue. i scrolled down to try again, and the 2nd time it worked. thats the same pattern i noticed with the error, just.. now, no error.

**Comment by CuriousMagpie** [comment]
Hi @vanathi-g -- are you making any progress on this? A few folks have been having problems with getting the orb to work per @saraolson's comment: they attempt to buy it for 0 gems, it doesn't work, and then they can buy it and it works--and charges them gems.

**Comment by saraolson** [comment]
> Trying to buy an Orb of Rebirth flashes up a "t.response is undefined" error and does not appear to do anything else?
> 
> UUID 	19e8f513-7273-4c7c-a121-45f537463b32
> User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
> Level 	124
> Class 	wizard
> Dailies Paused 	false
> Costume 	false
> Custom Day Start 	3
> Timezone Offset 	-600

**Comment by Mighil31** [comment]
Hello, I was trying to look into the issue but I'm not able to reproduce the error. I made a test account, edited it to lv 100 in mongo and then bought the orb. It worked and put me back to level 1. Also where exactly is this "t.response undefined" error supposed to show up?

**Comment by saraolson** [comment]
@Mighil31 the t.response undefined error shows up in the corner in a red message bubble.

**Comment by Mighil31** [comment]
@saraolson so here's what I'm doing
- Created a new user.
- Change user's level to 100 in mongo
- Complete a task which then creates the rebirth modal
- Buy the orb 
This works and I'm sent to the home screen as a level 1 warrior. I dont get any error either. I have tried on both chrome and firefox. Is there anything else that I should be trying ?

@rilygreat also mentioned these
```
Dailies Paused false
Costume true
Custom Day Start 0
Timezone Offset 420
```
Could these be the issue? I couldn't find any place to set them.

**Comment by ShivSitaram** [comment]
@Mighil31 @saraolson I tried what @Mighil31 did, and I'm not able to replicate the error. I've only tried it on Chrome, though. Looks like you tried Firefox.

@Mighil31 I'm not sure how those options could be the issue, but I'm not really able to see anything else that could be the problem...

**Comment by saraolson** [comment]
i just tested now and im still getting the previous behavior i commented where  the first orb purchase doesn't actually work, even though an error isn't showing anymore. this time it at least didn't seem to charge me gems on my 2nd try.

using firefox on an old account. went to settings > fix char values to set level to 100 for the free orb > market > buy orb there. it acts like it worked until reload, it doesn't show me a confirmation modal. but im still a level 100 mage and the 0 gem orb is still available (we have a time limit on free orb so if it worked, the orb would be 6 gems if bought again in 45 days).

looking at our server analytics, only one orb of rebirth is being recorded as actually happening when i did this. here's a vid:

https://user-images.githubusercontent.com/12453119/198066659-833a962d-b759-4fc3-b8c2-93be35ddb40a.mov

**Comment by CthonicSyzygies** [comment]
I'm having this issue again today. Happens exactly as described by the above posters. I'm level 75. I'm trying to purchase it because it's the first day of the new year. When I click, it asks me for confirmation, I confirm, and it refreshes the page; I've tried 3 times, and the third time I noticed the "t response undefined" message in the Habitica notifications.

The only thing I can think of is that I'm in a quest, but I don't think that would impact this.

Firefox, I created my account in 2013, anything else you would need?

**Comment by une4s** [comment]
This is happening to me today. I tried several times to purchase the orb. It seems to go through--the site refreshes, and everything is slowly reloaded, but I remain at level 101. I even tried leaving the quest I was in just in case that helped (it did not). Finally I tried it in Chromium (101.0.4951.15 (Developer Build)) rather than Firefox (109.0 build 20230109161414) and it worked. Chrome is an anti-privacy browser so it would be very nice if Firefox were fully supported.

**Comment by CuriousMagpie** [comment]
Another user having the problem:

>HI, I have an issue when I want to use the rebirth orb (I try to buy it in the market). The error message is "« rebirth_orb » not found". I try to do the same action in the website, when I try to buy it, the webpage refesh. In the 2 cases, nothing else happen, I can't go back to level one. Can you check this issue please ? thank you guys ;) :)

**Comment by slach123** [comment]
I also had this problem and tested many times on Firefox, fully refreshing the page, signing in and out, clearing cookies/cache and kept getting the t.response is undefined error. Tried in Microsoft Edge and worked first time. Please fix this so that Firefox users can have a complete experience. Like un34s commented Chromium is anti-privacy and I would hate for Habitica to force its user to use it.

**Comment by ctrueden** [comment]
In line with other comments here: I also receive the error when attempting to rebirth in Firefox, whereas it works in Chrome.

**Comment by gwisp2** [comment]
I attempted to examine this issue. While I couldn't replicate the 't.response undefined' error, I discovered that when clicking the 'buy' button, a POST request to /user/rebirth and a page reload occur simultaneously. When the page reloads, any ongoing requests get aborted. Therefore, if the rebirth request isn't sent quickly enough, it gets aborted.

**Comment by igromanru** [comment]
> I attempted to examine this issue. While I couldn't replicate the 't.response undefined' error, I discovered that when clicking the 'buy' button, a POST request to /user/rebirth and a page reload occur simultaneously. When the page reloads, any ongoing requests get aborted. Therefore, if the rebirth request isn't sent quickly enough, it gets aborted.

Hello, I'm currently experiencing the issue. Is there a solution yet?

**Comment by ctrueden** [comment]
@igromanru I still experience this issue in Firefox. As a workaround I just use Chrome to rebirth. :sweat_smile:

Based on what @gwisp2 said above, the culprit is probably [this code block](https://github.com/HabitRPG/habitica/blob/27eedaf34743ff899f46da8302b80e146b871dc5/website/client/src/components/shops/buyModal.vue#L843-L845), which explicitly reloads the page immediately in response to an orb of rebirth being purchased. It was introduced intentionally in #11125, in an effort to address #11114, but it seems we now have to deal with this bug instead.

@HydeHunter2 @Alys Is there a way to have our cake and eat it too, maybe by adding a delay to the reload, or doing it asynchronously after the orb of rebirth POST operation has completed successfully? Or is @gwisp2's theory here incorrect?

**Comment by igromanru** [comment]
It worked for me on the Android Firefox app.   
What I don't understand is why Orb of Rebirth doesn't exist in the app version of Habitica.

**Comment by anishlukk123** [comment]
@CuriousMagpie  can I work on this

**Comment by CuriousMagpie** [comment]
@anishlukk123 I'm going to take this one.

**Comment by CuriousMagpie** [comment]
I've determined that the `t.response undefined` error is unrelated to Firefox users being able to purchase the Orb of Rebirth. I am going to be making a new issue for that, as it is resolved in #15300. I'll also be cleaning up the comments here so they're only relating to `t.response undefined`, so as to not muddy the waters.

**Comment by saraolson** [comment]
had a user report that they were unable get the orb of rebirth to take effect on firefox. eventually they were able to repeatedly try and get it to work, still seeing the t.response error ofc. just dropping this note here that firefox users still occasionally have issues with the orb of rebirth not working on initial purchase.

 84730032-2f2b-4d1c-a5d2-647b506d829c

**Comment by Hafizzle** [comment]
This should be fixed w/commit https://github.com/HabitRPG/habitica/commit/9dd57d77076c4f425cfff68fb42a97da3f00d720

**Comment by fentie** [comment]
Looks like that commit hasn't been merged yet? I just hit this issue less than an hour ago, and switching away from Firefox fixed it.

**Comment by Hafizzle** [comment]
> Looks like that commit hasn't been merged yet? I just hit this issue less than an hour ago, and switching away from Firefox fixed it.

Hi @fentie, not yet - this fix is part of a larger bugfix PR that I'm currently addressing feedback on. Working to get it merged, thanks for your patience!
