### ISSUE TITLE
Scrolling causes page to white-out

### ISSUE THREAD

**Issue by soar9** [HabitRPG/habitica#2008]
I'm having a strange issue. When I go to the HabitRPG site (on Internet Explorer) it loads normally, but if I try to scroll down at all, say, to see the rest of my tasks, the task portion of the screen whites out. I can still see the avatar and health bars, but no tasks, or tavern chat if I'm in that area. If I scroll back up, it reappears, but then I still can't get to the bottom tasks.

**Comment by bekahbou** [comment]
I am having the same exact issue, and also on the inventory page.

**Comment by lefnire** [comment]
Gotta restore back to Zakkain's old header css, this is using Bootstrap Affix which is really bad in this case. It also breaks tours. Bumping prio

**Comment by lefnire** [comment]
can you test this now?

**Comment by bekahbou** [comment]
The problem is still happening. 

----- Original Message -----

**Comment by lefnire** [comment]
Hmm, not sure I'll be able to easily fix this. Can you try a hard refresh? What about using a different browser? What version of IE are you using (FYI, I know it's a terrible answer, but IE very often gets the shaft for web apps, so if it can be helped dev always recommend users not use IE in general)

**Comment by soar9** [comment]
The problem is resolved when I use Chrome, but not IE. I know it's my fault for using IE, though. :)

**Comment by lefnire** [comment]
Try one last thing,  uncheck Settings > Sticky Header.

**Comment by bekahbou** [comment]
I tried to sign into habitrpg using google chrome and it didn't recognize my account, so I can't check if it works on there. Still doesn't work on Internet Explorer though, and it worked fine until this morning. Also I don't know how to find settings > sticky header. 

----- Original Message -----

**Comment by soar9** [comment]
I did uncheck Sticky Header, but it does not help the issue on IE, sorry.

**Comment by lefnire** [comment]
Alas. A bug we'll have to toss in on

**Comment by lefnire** [comment]
I feel weird doing this.. but closing without fixing :/

**Comment by bekahbou** [comment]
That's ok - I got it to work on Chrome, so i'll use that from now on. Thanks for your help. 

----- Original Message -----

**Comment by Zian** [comment]
I'd like to reopen this bug with the following repro:

Environment: IE11, Win7 SP1 x64, 100% zoom on a widescreen monitor

Go to habitrpg.com and let yourself be redirected to https://habitrpg.com/#/tasks
Click on "Options"
Click "Settings"
Scroll down

Here are the errors I get with F12 (developer tools) open:

   SCRIPT445: Object doesn't support this action
   File: habitrpg.com, Line: 32, Column: 429
   SCRIPT445: Object doesn't support this action
   File: habitrpg.com, Line: 32, Column: 429
   SCRIPT445: Object doesn't support this action
   File: habitrpg.com, Line: 32, Column: 429

I tried clicking on "Line: 32, Column: 429" and was redirected to the following line:

```
{invite.profile.name}}</span></a></td></tr></table></div><div class="modal-footer whatever-options"><form 
```

The cursor was placed right before the "/" in the `</tr>` tag.

My user ID is `90145e45-71ca-4c83-8ecf-703e40ccdcda`.
