### ISSUE TITLE
Progress Scale Problems

### ISSUE THREAD

**Issue by Gragriel** [HabitRPG/habitica#219]
I see a lot of instances in my Progress graphs of long horizontal lines, which show multiple data points from the same day. This really throws off my sense of time-scale with the graphs. My guess is that the points are plotted with "data point #" or something as the horizontal axis, even though the axis is labelled with dates. Is there a way to plot the points by day or time, so same-day data points don't just show up as a horizontal line?

**Comment by horusofoz** [comment]
@SlappyBag @lefnire I'm not sure of the difficulty in coding this so could one of you brilliant devs triage?

**Comment by Pandoro** [comment]
I'd say if the points are stored, it should be fairly easy to sum them together if they are made within the same day. Then you can plot the same mechanism which it is plotted with now, just use the new data. Looks clean, should be easy. I'm just not sure about the scalability, if we play for a long time, summing over the points might get messy, but I guess we will not play long enough to reach this point sooo ^^ 

say lifespan \* days \* 10/day = somewhere between 250k and 350k Should be a piece of cake.

**Comment by StanLindsey** [comment]
This shouldn't be too difficult depending on how its currently implemented, at some point I think we're going to export all the data so that the individual points don't need to be queried but as @pandoro says it shouldn't be too terrible. =D

**Comment by horusofoz** [comment]
@zakkain Has this issue been resolved with your re-implementation of the history function?

**Comment by Gragriel** [comment]
I'm still seeing the issue, unless the re-implementation @horusofoz is referring to isn't official yet. Another possible fix I thought of would be to use the same data points to plot as before, but change the plot format to be a scatter plot and have the x axis be "date/time" rather than "index" or whatever it is now. Mousing over each part of the plot shows date, so that information should already be in the point. The downside there could be each date showing multiple points squished together, if we use "date".

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
