### ISSUE TITLE
didn't level up when I hit 20/20 exp?

### ISSUE THREAD

**Issue by atuttle** [HabitRPG/habitica#236]
I'm level 1, on the cusp of level 2. This morning, this happened:

![](https://www.evernote.com/shard/s240/sh/49c08a05-e7d8-4b0b-945a-d05f08d301a9/dfe950a9b528ac22545c5df72645999a/deep/0/Screenshot%201/27/13%2012:54%20PM.jpg)

It still looks exactly like this after a refresh, too.

I got my last EXP point from a habit `+`, and the habit in question doesn't have a `-` option -- if that helps debug. :)

**Comment by svemir** [comment]
I think it goes up on your NEXT point.

**Comment by lefnire** [comment]
one current bug is that any API modification to your stats (eg, chrome extension) don't level you up - only manual habits. sounds yours was manual, might be what @svemir pointed out.

**Comment by StanLindsey** [comment]
Yeah, I experienced this with the Chrome Extension, after you complete a task manually it'll all cross over. 
I mentioned it here
https://github.com/lefnire/habitrpg/issues/141

I'm close my one and label this as bug as this issue has more detail/discussion.

**Comment by mgatten** [comment]
I've seen this on every level up - not using any API. The first time, I thought it was a bug. By the third time I figured it was just working as designed. For instance, the top of level 4 is eighty. It's like level four contains slots for 80 points. When you fill up all those slots, you're still level four. You don't go up until you overflow the slots with your 81st point. And then that one goes into the first slot of level 5. It's not quite what we're used to as RPG players, but it makes its own kind of sense.

**Comment by horusofoz** [comment]
Is this still an active issue?

**Comment by dbueller** [comment]
Yes.  I know where the trouble is.  Do you code?

**Comment by StanLindsey** [comment]
Its still a bug, its just not a priority at the moment. I code though @sabin144 if you've already spotted the problem.,

**Comment by dbueller** [comment]
It is a very simple thing.  Line 167 of the index.html looks at the user's current exp, but it is rounding it.  Truncating instead of rounding would be more appropriate.

**Comment by horusofoz** [comment]
@sabin144 Sadly I don't yet have such magic skills :(

**Comment by dbueller** [comment]
Yeah.  I'm not very familiar with html/JS/CSS myself.  I could have fixed it in R.  I'm still working on getting up to speed.

**Comment by StanLindsey** [comment]
Yeah, I guess its rounding the number after a check has been made to see if the user has actually got 40/40. So 39.7 would fail the check and then it would be rounded to 40.

So I replaced  
<i class=icon-star></i> {round(_user.stats.exp)} / {_user._tnl}

with
 <i class=icon-star></i> {Math.floor(_user.stats.exp)} / {_user._tnl}

Only issue is people will loose up to 0.9 experience each time they earn any but its a quick fix visually.

**Comment by dbueller** [comment]
I tried that, but I don't think the index.html has access to that library.

Error: view function "Math.floor" not found for call: Math.floor(_user.stats.exp)

As it is since it is rounding anyway, they only see the whole number.  This won't actually change how much XP the user has, only how much is displayed.

**Comment by Pandoro** [comment]
Loose in the sentence means loose visually right? Not Loose as in loose
real exp?

**Comment by StanLindsey** [comment]
Typo, I meant lose.

**Comment by dbueller** [comment]
No XP would be lost.

**Comment by Pandoro** [comment]
Urg, well it was a typo on my side too... I need to sleep more x) I meant
to ask if this would mean if we lose exp yes or no, but Sabin144's comment
kind of pointed it out already :) Thanks

**Comment by StanLindsey** [comment]
Well I got to run for an hour so I couldn't faff around long enough, I put it back to normal so my pull request doesn't break anything.

**Comment by dbueller** [comment]
I'm off for a couple of hours too, but I'll keep working on it.

**Comment by horusofoz** [comment]
Is anyone still looking at this? Is it active?

**Comment by mgatten** [comment]
Funny this popped up today. I thought it had been fixed weeks ago, but just last night I was surprised to see that it still happens. So it's still an active problem, if that's what you're asking. Is it active in the sense of being worked upon? No idea.

**Comment by lefnire** [comment]
I'll fix this eventually, it's just _quite_ minor compared to other bugs.

**Comment by mgatten** [comment]
Oh, no doubt! I totally agree and didn't mean to sound like I was whining about it. I was just answering the question that it is still active in case others weren't still aware, and expressing surprise since I'd read about a solution a while back and thought was implemented. As far as priorities go, this one should be pretty close to the bottom of the list.

**Comment by lefnire** [comment]
Oh gotcha!

**Comment by Pandoro** [comment]
Should be fixed with the new system :)

**Comment by horusofoz** [comment]
@atuttle As @Pandoro advised, this should now be fixed, can you confirm?

**Comment by Pandoro** [comment]
@horusofoz, this will be hard to confirm, as you would need to simulate the
rare case where you get current_exp = max_exp - x, where 0 <= x <= 0.5

Especially with the large amounts that is hard to replicate :x

**Comment by lefnire** [comment]
this should fix it: https://github.com/lefnire/habitrpg/pull/591/files , @MrConcept to the rescue once again!

**Comment by junglist** [comment]
This problem still happens for me, should this be fixed? I'm using the chrome extension. I added a habit manually and +'ed it then it checked and levelled up correctly. 
![Screen Shot 2013-03-07 at 9 16 37 AM](https://f.cloud.github.com/assets/3763947/231304/67ab4050-8700-11e2-9be2-6e0ca8ba8e9b.png)

**Comment by PhilipHow** [comment]
I'm pretty sure the API will still cause the issue... I'll see about putting up a temp fix.

**Comment by lefnire** [comment]
Yeah, it's the API. model.on listeners are what level you up, which don't
trigger on the server
