### ISSUE TITLE
Too much XP given for task completion (ie a good problem to have)

### ISSUE THREAD

**Issue by leupagus** [HabitRPG/habitica#3205]
I had a three-checklisted task that I put up almost entirely for the sake of immediately checking it off (hopefully I'm not the only one who does this); it was a five-minute-old task, in short. When I ticked off the three checklists and then ticked the "completed" box, however, I got 800 XP, 7 gold coins and change, and leveled up from midway through 35 to midway through 36. There was no notification that there was anything special about what I'd done (ie, no "critical hit!" mention), so I'm not sure what happened.

I went in to the "completed" tasks and un-checked it; this resulted in getting 14 XP deducted. Then when I went back to the Tasks page and re-checked it, this time it gave me 57 XP. So I now have about 843 more XP than I deserve. Not sure if it's a problem per se, since it's cool and all, but if it's happening to other people it might be indicative of a larger problem.

ETA: I'm a complete and utter moron. We finished the Spring Quest at the same time - the 800 XP comes from that, not from my task completion. Sorry for wasting time.

**Comment by BlackEdder** [comment]
@leupagus Since the issue is solved, would you mind closing it?

**Comment by leupagus** [comment]
Sure - tell me how to do that and I will.

**Comment by deilann** [comment]
This is actually the issue of todos being unchecked removes too little XP. That issue isn't solved, but that's the proper ticket. https://github.com/HabitRPG/habitrpg/issues/2222
