### ISSUE TITLE
Don't show notifs button, or change its appearance, if no new notifs available [$10]

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3270]
In the new interface on Beta, there's a handy speech-bubble button that drops down to show all your Guild and Party notifications. However, it looks the same whether or not you have new notifications to view, which is a loss of functionality vs. the UI currently on Main. The button should disappear, or look different (lower opacity? different icon?) when there are no new notifs. If it sticks around, clicking it should produce a "no new notifications" message, maybe with an additional link to jump to the Social tab.
##

**Comment by wc8** [comment]
:+1: 

I lean toward a very **light grey** icon for no messages and a _dark grey_ (current color) icon for messages, since some users don't want the notice to be too distracting. 
(I'm assuming two shades of the same color would work for colorblind users).

From the mockup, I'm thinking there's eventually a plan for a blue icon+ **@** symbol for mentioned me notifications? Am I wrong? @benmanley

**Comment by benmanley** [comment]
@wc8 @Sabrecat Great minds think alike. We’ve actually added exactly that, but to make it work I think @paglias needs to do something to:

https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L257-L260

In my mockup, the icon is blue because we were thinking of giving particular guilds and parties a colour. Then the colour of the notification icon would reflect the colour of the guild that sent the most recent message. 

This would take a bit of work to implement and the plain icon is probably less distracting anyway, so I don’t know if it’s necessary.

Adding an @ for mentions would still be good, but I have no idea at the moment how mentions work!

**Comment by paglias** [comment]
@wc8 @SabreCat @benmanley sorry for the absence! it's fixed here https://github.com/HabitRPG/habitrpg/commit/a9f80bd860e34f687d69c3dddb730d0f52b6866e but won't change anything unless you register now, @lefnire should run a migration the removes from the database all the `undefined` keys in each user's newMessages:

![selezione_054](https://cloud.githubusercontent.com/assets/589911/2764677/d0d8cece-ca18-11e3-92e4-a0433013d5fc.png)

**Comment by lefnire** [comment]
`db.users.update({},{$unset:{'newMessages.undefined':1}},{multi:1})` look ok?

**Comment by paglias** [comment]
@lefnire :+1: ! thanks

**Comment by SyntaxPickax** [comment]
Any progress on this?

**Comment by paglias** [comment]
This has been fixed for many users but it looks like for someone is  still
persisting, including me (newMessages: {undefined:{value:false},....)

2014-06-30 16:32 GMT+02:00 SyntaxPickax notifications@github.com:

> Any progress on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-47538559.

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
Oh, I didn't know that it had been fixed for many users. I'm one of the
ones who still has to check manually.

On Mon, Jun 30, 2014 at 12:33 PM, Matteo Pagliazzi <notifications@github.com

**Comment by SyntaxPickax** [comment]
I also have to check manually.

**Comment by SabreCat** [comment]
Huh! Yeah, the button always has a speech bubble icon in it for me.

**Comment by deilann** [comment]
A workaround awesome fix might be to have a "Clear all notifs" button for
when I have like 8 notifs and don't want to think about them. It could not
only clear those notifs but then define newMessages, so no need for a
migration.

**Comment by SyntaxPickax** [comment]
Sounds like it's still an open issue. I put a $10 bounty on it.

**Comment by deilann** [comment]
pinging @lefnire -- was the migration ever run?

**Comment by paglias** [comment]
Ok for new users is fixed and has been so for at a few months (https://github.com/HabitRPG/habitrpg/commit/a9f80bd860e34f687d69c3dddb730d0f52b6866e), for old ones it looks like the migration wasn't run

**Comment by wc8** [comment]
I'm not sure about that. inkwell's account is just a few weeks old and still seeing a dark grey notification button regardless of whether there are any messages for her. 

> dde4a7b7-3399-4690-9f3c-9ec312e604e3
> - Member since  06/07/2014

**Comment by paglias** [comment]
Mmm strang I tried creating a new account and it was fine

2014-07-02 1:34 GMT+02:00, wc8 notifications@github.com:

> I'm not sure about that. inkwell's account is just a few weeks old and still
> seeing a dark grey notification button regardless of whether there are any
> messages for her.
> 
> > dde4a7b7-3399-4690-9f3c-9ec312e604e3
> > - Member since  06/07/2014
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-47721556

## 

Matteo Pagliazzi - paglias.net

**Comment by SyntaxPickax** [comment]
Any progress? Someone want to attach the bounty label to this issue?

**Comment by paglias** [comment]
I think that we just need to run the migration @lefnire

2014-07-30 18:53 GMT+02:00, SyntaxPickax notifications@github.com:

> Any progress? Someone want to attach the bounty label to this issue?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-50645342

## 

Matteo Pagliazzi - paglias.net

**Comment by deilann** [comment]
Oh, I thought the bounty label auto attached.

**Comment by lefnire** [comment]
@paglias I ran `db.users.update({},{$unset:{'newMessages.undefined':1}},{multi:1})` a while back, should I run something different? Want me to run the same migration again?

**Comment by paglias** [comment]
@lefnire ok... I thought you might have missed it among all the other things. then we should probably come up with something new I think because it looks like the issue has been fixed for new users but the migration didn't work.

**Comment by lefnire** [comment]
I'm running it one more time for good measure

**Comment by deilann** [comment]
What if clicking the bubble set it to no new notifs? Because if you clicked
it, you've seen the notifs that are in there and have chosen to ignore them
or at least know they're there. Then, this would be self-healing.

**Comment by paglias** [comment]
@lefnire I've added a new migration that in my tests on an object returned from the api works https://github.com/HabitRPG/habitrpg/commit/9d2723b4186cd19a7b7f754f292f3c783d0c6ac4, if you could double check it before running it, it would be great

**Comment by Alys** [comment]
The problem of the notification button always indicating that there's new messages -- isn't that happening because there's a discrepancy between how we check for new messages and how we "delete" notifications for messages we've seen?  We check for new messages by asking if user.newMessages is empty (https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/menu.jade#L108 and https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/menu.jade#L115) but we remove the newMessages flag for a guild by setting its value to false (https://github.com/HabitRPG/habitrpg/blob/develop/public/js/services/groupServices.js#L50 and https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/groups.js#L261) meaning that user.newMessages is never empty. For example, here's my json data when I have no new messages:

```
    "newMessages": {
        "undefined": {
            "value": false
        },
        "f847a531-8ea5-4ba9-b6c5-7d99a7d17ea8": {
            "value": false,
            "name": "Pax"
        },
        "e655bb46-96ec-4d8b-b40d-f195063904c8": {
            "value": false,
            "name": "The developers guild"
        },
       etc
```

Even if we got rid of the undefined guild, newMessages still would be triggering new message notifications because it's not empty. 

Is there any disadvantage to changing the code so that when we've seen a guild's messages, we delete that guild from newMessages instead of setting its value to false?

**Comment by Alys** [comment]
Also I'm wondering if the undefined guild keeps appearing because of this: https://github.com/HabitRPG/habitrpg/blob/develop/public/js/services/groupServices.js#L47-51
Are there any circumstances under which that could be run when gid is undefined? This is just a wild guess; I haven't worked through the code to find out all the ways it could be called. If it happens to be a lucky guess, then putting "if (gid)" in the function and running the migration command one last time might fix the undefined guild.

**Comment by AdrienLemaire** [comment]
Issue fixed in #3860, as noticed by @SabreCat , but I just hide the button instead of making a light grey icon.

The fix being very simple, I don't feel like claiming the bounty. But thanks for the attention @SyntaxPickax, much appreciated!

**Comment by Alys** [comment]
@Fandekasp : I think your PR is more of a temporary workaround rather than a permanent fix because it adds additional code and processing time. The styles already on the notification icon should be sufficient to grey-out the icon when there's no notifications (and that's preferred over hiding the icon because we'll get  repeated Tavern questions from users asking why their notification icon has disappeared). This is not to say that your solution shouldn't be used while we work out a permanent fix.

I've done some brief experimenting with the code I was talking about above, and it seems to be relevant. On my local install, whenever my test user visits the party page, the "undefined" guild entry is inserted. If I add the `if (gid)` statement that I mentioned, then that no longer happens. Also, in groupServices.js, using `if (User.user.newMessages) delete User.user.newMessages[gid];` instead of setting newMessages[gid].value to false allows the greyed-out style to take effect. But, there might be other consequences to deleting it - if there a reason it's being kept but set to false?

I have not yet worked out how to change the api.seenMessage function to delete rather than set value=false. 

@Fandekasp, since you've been working on this issue already, would you like to keep investigating the existing code? I don't need the bounty. :)

**Comment by AdrienLemaire** [comment]
I see, makes sense.

Unfortunately I'm very busy, just had a little bit of time yesterday. Better not count on me for further improvements since I don't know when I'll be able to help again :-)

**Comment by Alys** [comment]
I'm working on this now (the proposed fixes I described in my comments above).

**Comment by jakerella** [comment]
As you're working on it, if it's possible to add a count fo the number of notification "channels" that would be great!

**Comment by Alys** [comment]
Adding a count to the notification icon is a very different thing and will be best done with a separate change. This issue is to fix intended behaviour that's currently broken. I'm not against a count being visible, but I won't be including it in this fix.

**Comment by SyntaxPickax** [comment]
Unless I've missing something, the notification icon still looks the same when there are unread notifications and when there are none. Is this really closed?
![screen shot 2014-11-03 at 8 40 36 pm](https://cloud.githubusercontent.com/assets/1245093/4894918/eee31204-63dc-11e4-8638-01c7caac7f08.png)

**Comment by Alys** [comment]
The code change required was merged (which is why this became closed) but a database script still needs to be run to clear out old data. https://github.com/HabitRPG/habitrpg/pull/3936

**Comment by SyntaxPickax** [comment]
Ah, OK. Thanks.

**Comment by SabreCat** [comment]
Gonna reopen until this is fixed for reals.

**Comment by Alys** [comment]
I believe the only thing needed for this is for this migration script to be run: https://github.com/HabitRPG/habitrpg/pull/3936

If nothing else, it's a necessary step, to clear out old, bad notifications.

**Comment by Alys** [comment]
I ran that migration script a couple of days ago and since then my notification icon has been turning grey as expected.

In a private chat on 6 February, paglias said this: "_@alys: do you remember that migration to fix notifications' icon? Going through the requests made by the page on load I still have a /api/v2/groups/undefined/chat call :disappointed: so even running it wouldn't solve the problem_"

I don't yet know where that call is coming from. I haven't yet seen it myself. I'm leaving this issue open until we sort that out, or until enough time passes that it's clear that the migration script fixed the problem.

**Comment by Alys** [comment]
I just now was on the guilds index page, then I clicked into one guild, and then saw the message below in the console. However the notification icon stayed grey.

```
app-bed45c9e.js:8 TypeError: Cannot read property 'chat' of undefined
    at Object.a.chatChanged [as fn] (app-bed45c9e.js:43)
    at j.$get.j.$digest (app-bed45c9e.js:10)
    at j.$get.j.$apply (app-bed45c9e.js:10)
    at app-bed45c9e.js:10
    at p (app-bed45c9e.js:6)
    at app-bed45c9e.js:6
    at nrWrapper ((index):1)
```

**Comment by paglias** [comment]
@Alys seems to be working!

I just checked and the cal to `/api/v2/groups/undefined/chat` is still there but doens't seem to be causing any harm:

![selezione_001](https://cloud.githubusercontent.com/assets/589911/6941924/0905b882-d884-11e4-95c0-32f98c8e6ce1.jpg)

And that error you saw I don't think it's related

**Comment by SyntaxPickax** [comment]
I'm so pleased to see this finally working.  Thanks!
