### ISSUE TITLE
Can't add new habit?

### ISSUE THREAD

**Issue by ZdenkaWaldner** [HabitRPG/habitica#330]
I've just started my account. When I try to add a habit, the game pops up information about inviting other people/creating a party, and if I dismiss it then it won't add the habit. Help, I'm confused.

**Comment by lefnire** [comment]
@danj3ris @ZdenkaWaldner what browser y'all using?

**Comment by ghost** [comment]
Happened to me on my phone using Chrome.

**Comment by ZdenkaWaldner** [comment]
Firefox.

**Comment by ShadowBan** [comment]
Same for using Chrome 26.0.1403.0

**Comment by danj3ris** [comment]
Using SRWare Iron, a privacy focused modified Chrome. Basically Chrome.

**Comment by gmeben** [comment]
I've tried adding new habits in both Firefox 18 and Chrome 24.

In Firefox, it doesn't do anything, but in Chrome, a modal window appears asking me to invite others to my party.

Definitely related to **Party System bugs**

**Comment by lefnire** [comment]
This is pretty critical, will be my first order of business.

For those who are experiencing the bug, is the party system enabled? (in the user dropdown). Is it when you click "Add", or when you click in the text box, or what? Trying to reproduce on all the browsers I can get my hands on, no cigar - and I can't think of what could be causing this, so gotta get as much info as I can.

**Comment by ZdenkaWaldner** [comment]
Using Firefox. I'm no longer getting the Party pop-up when I try to add a habit. It will let me type in the text box, but nothing happens when I click the "add" button.

I don't see anything that would let me add a party if I wanted to do that  -- clicking on the dropdown gives me options of "settings" and "logout." None of the settings have to do with Party options.

**Comment by lefnire** [comment]
Crazytown! I don't want to throw too much at you, but in case you're
willing - if you use Firebug, or have Chrome handy and know how to open up
"console". Open console/firebug, then click add, and what error do you see?

**Comment by gmeben** [comment]
Using Chrome 24 again, and like @ZdenkaWalder, I'm not seeing any Party System enablement in the user dropdown.

The `#party-modal` only appears when I attempt to create a new habit.

The only observable methods of closing the `#party-modal` are to click outside of the modal or click "Leave" and when I do, it consoles: `GET https://habitrpg.com/img/BrowserQuest/habitrpg_mods/weapon.png 404 (Not Found)`

**Comment by gmeben** [comment]
Whoa! I did a hard refresh and the habit system works as expected. Bug might be fixed, but I'd wait until others report before I'd close this.

**Comment by lefnire** [comment]
hmm, ZdenkaWaldner can you try a hard-refresh? [Firefox hard refresh](http://ascherconsulting.com/how/do/i/perform/a/hard/refresh/in/firefox/) - it could be that the browsers cached the old HTML which isn't compatible with the new code?

**Comment by gmeben** [comment]
Just to be clear, I think my hard refresh may have just been coincidental with the "fix" because I recall glimpsing the interface changing just before I refreshed.

**Comment by ZdenkaWaldner** [comment]
I'm a little confused about what a hard refresh is, but I pressed CTL-F5 like the instructions said and that didn't help. I also closed Firefox and then opened it again, which also didn't help.

**Comment by gmeben** [comment]
You've got it; CTL+F5 is a hard refresh in Windows Firefox. It basically bypasses the cache to display what's (theoretically) current on the server. Sometimes, browsers are stingy and need to be kicked in other ways to display what's currently on the server.

But like I said, this is probably quite unrelated to the bug at hand.

**Comment by lefnire** [comment]
I did a push recently which, while not directly addressing this issue, effects the same components - could any of you  test again?

**Comment by Bquilt** [comment]
Cannot add habit.  Account opened this morning on Chrome where the "party" issue occurs.  Have also tried Firefox.  No option on settings related to party.

**Comment by gmeben** [comment]
The habit functionality appears to still be working on my end. Everything appears really normal. Still no "Party" option in the user dropdown.

**Comment by lefnire** [comment]
PS, parties are unlocked at lvl 3 is why some of you aren't seeing it. It sounds like the issue is specifically the "add" button not creating a habit.  I'll keep playing with this, but nobody is getting an error in Chrome console or Firebug when they click add?

**Comment by Bquilt** [comment]
For reasons that are a complete mystery to me, habits now add properly in Chrome for me.

**Comment by lefnire** [comment]
it could a cached version of your page being invalidated (aka, hard refresh). Let's get a tally, who's still having this issue? and is it still the same (party popup, no task added)?

**Comment by redwoodfey** [comment]
I'm on Firefox and unable to add a habit. It was working fine until I had to reset my account because I accidentally used gold when I was trying to edit my rewards system. Now nothing happens when I click the add button in the Habits section. Tried a hard refresh, opening and closing browser, and logging in and out of account.

**Comment by ZdenkaWaldner** [comment]
On Firefox, still cannot add habit. The party popup has stopped happening -- now just nothing happens when I click the "add" button.

**Comment by lefnire** [comment]
Ok. Well, thanks again guys - just so everyone knows, this is # 1 priority for me right now. I'm stumped by it, even step-through debugging, simply because I can't replicate on my own system. I might try another system soon. I'll keep everyone posted, and I'm so sorry for this.

**Comment by ghost** [comment]
I can add a habit just fine... Using chromium latest version 64bit Ubuntu 12.10 64bit

**Comment by redwoodfey** [comment]
Update: seems to be working like a charm right now. Not sure if this has anything to do with it, but I used it on boyfriend's computer using Chrome where it was working just fine, then I went back to my computer and Firefox and it started working. Thank you! Absolutely loving this so far.

**Comment by Bquilt** [comment]
Odd - When I setup the account this morning it did not work.  On Chrome I got the "party" link.  When I tried on Firefox I got nothing.
Now, it works on both Chrome and Firefox.  When it was not working I closed out of both browsers and reopened them, still nothing.  At some point, I know not when, but for sure without closing out of Chrome, it started working again.

In anycase, I'm not a gamer but this is a great app!  Also - although I have a smartphone - I like the fact that it's on the web and don't have sync issues....

**Comment by gmeben** [comment]
All systems go for me in the following browsers on Windows: Chrome 24, Firefox 18, Safari 5, and IE9

**Comment by Spade6179** [comment]
Still having problems here, even after restarts and hard refreshes. From my perspective, the "Add" button isn't aligned to the entry box, being several pixels below it. Every other button works fine. Using Firefox 18.0.2.

I like the prospect of the project, so I hope it becomes fully functional soon.

**Comment by lefnire** [comment]
@Spade6179 can you [email me](mailto:tylerrenelle@gmail.com) your uuid (or registered email / uname) ? I wanna test disabling ads to see if that's what's causing issues

**Comment by Spade6179** [comment]
Done.

**Comment by Spade6179** [comment]
Update: Disabling Ads did not work. Still investigating cause.

Does anyone have any suggestions on other ways to isolate the problem?

**Comment by Spade6179** [comment]
Update: Alright, it should work now!

**Comment by lefnire** [comment]
well... maybe that did the trick, but I'd be surprised - we'll keep this open for a while and see if it fixes for everyone

**Comment by Mastrie** [comment]
lefnire, I'm still having the issue. Chrome V 24.0.1312.57. No errors showing.

**Comment by meganstrickland** [comment]
In Firefox 18, I can type in the box, but nothing happens when I click Add. Same as Spade6179, the Add button isn't aligned to the entry box, being several pixels below it.

In Chrome, the Add button is aligned, but I get the party invite pop-up when I click it.

I'm running Windows 7, if that makes any difference. I tried disabling my ad blocker, but no change. Please let me know if there is any other information that would be helpful.

Thank you for all that you do!

**Comment by Mastrie** [comment]
For me, the problem only appeared after I did a reset. Perhaps there is some connection there.

**Comment by ericwilmoth** [comment]
I use firefox, so I decided to try it in chrome; worked there, went back to firefox, then it finally worked! weird.

**Comment by lefnire** [comment]
That push throws something into console I want to test, it will be deployed in a few hours. Later tonight or tomorrow I want to setup a a virtual machine with some common-denominator environment to see if I can replicate, pretty hard to debug at this point. 

I removed ads (now that we have pets in), but that doesn't seem to make a difference anyway. Just so everyone knows, even though this one is dragging on it's on the forefront of my mind

**Comment by Mastrie** [comment]
I'm not sure if you just fixed it, but it started working for me.

**Comment by lefnire** [comment]
Ok, new theory. The entire DOM, including data-view bindings, is reset under certain circumstances (see [this codeblock](https://github.com/lefnire/habitrpg/blob/master/src/app/browser.coffee)). Those circumstances being: user reset, reroll, cron (beginning of the day, when your dailies are reset), and any Parties activity (add new member, join, leave, etc). You can see I commented out the re-registering of existing `refLists` on [line 7](https://github.com/lefnire/habitrpg/blob/master/src/app/browser.coffee#L7), it was causing issues.

I'm wondering if this is what's happening for some people. The next time you can't add a task, try a refresh and try again (the second reload shouldn't cause DOM reset).

**Comment by lefnire** [comment]
Ooh, I got it to replicate! For some reason the habit input box isn't being surrounded by the `<form>` tag in certain circumstances, I haven't yet figured out what triggers it - but I got it replicating on my local, so I'll play. In the mean time, the workaround is to 

add habit -> party dialog pops up -> click outside the dialog to close it -> you can now add a habit

**Comment by lefnire** [comment]
Got it! Was an unclosed `</form>` that was only present in certain circumstances, and many browsers close it for you automatically - but not with all the DOM magic that goes on in Derby, so it was super intermittent. We're fixed fellers

**Comment by ZdenkaWaldner** [comment]
YAY it's working now. :) Thanks for all your hard work.

**Comment by lefnire** [comment]
Thanks for all your hard patience ;-)

**Comment by ghost** [comment]
When I try and uncheck a habit it deletes itself. I can add a habit just fine though.

**Comment by StanLindsey** [comment]
Do you mean uncheck a daily, downscore a habit or unchecking the Up/Down items within the habit?
