### ISSUE TITLE
partial translation in drop notes

### ISSUE THREAD

**Issue by liordon** [HabitRPG/habitica#3531]
@paglias 

in the messages section, the message for finding a potion is:
You've found a <%= dropText %> Hatching Potion! <%= dropNotes %>
problem is, the dropNotes themselves, when inserted into the message are not fully translated. example:
![image](https://cloud.githubusercontent.com/assets/4543336/3077936/36568104-e44c-11e3-9528-d94c4f6e3d3a.png)

here the hebrew translation of zombie (which is still zombie, but transliterated) appears in the droptext but in the drop notes it appears in english. any ideas?

**Comment by liordon** [comment]
also, this happens when I feed my pets:
![image](https://cloud.githubusercontent.com/assets/4543336/3085736/5aa4a0cc-e519-11e3-8854-8baff7af5c9a.png)

I'll just mention that hebrew is 100% translated

**Comment by deilann** [comment]
That looks like you're not even getting the English strings -- you're
getting the string names. In English, it would be "Cotton Candy Pink Panda
Cub" not "CottonCandyPink PandaCub"

**Comment by liordon** [comment]
perhaps it's the same problem in both cases. 
to check what you said, I tried this in other languages. first, english:
![image](https://cloud.githubusercontent.com/assets/4543336/3087887/a2e72da6-e563-11e3-9619-1cb1f461cabd.png)
this already shows the problem probably existed for a while now, we just haven't noticed since we all probably skim over these messages (who wouldn't?)
same thing in german:
![image](https://cloud.githubusercontent.com/assets/4543336/3087902/ed3bae90-e563-11e3-9bdb-d63931156b5e.png)
and so forth. how much JS do you think I need to know in order to fix this?

**Comment by deilann** [comment]
i18n is @paglias' baby. He should be able to get on this pretty soon. :)

**Comment by paglias** [comment]
@deilann @liordon working on this, the string without spaces in "feed ..." is probably due to the fact that it's not using translations..

**Comment by paglias** [comment]
@liordon the popups are fixed https://github.com/HabitRPG/habitrpg/commit/df8eb107cda3cd78f59735cd63547242fbb81620, the drop messages are sometimes incorrect and still wondering why, but it only happens in production, for example I can't replicate on my local install

**Comment by liordon** [comment]
have this fix been pushed back to the site? It's been some time now and this bug is still in effect.

**Comment by lefnire** [comment]
I did a deploy ~20h ago

**Comment by paglias** [comment]
@liordon I've just checked and the popups are fixed, fot the drops notifications it is a more general bug but I'll try to come up with a solution about this one specific today

**Comment by paglias** [comment]
Tyler, I noticed that after the drop is calculated some variables are
updated (incremented by one) (give a look to the code in habitrpg-shared,
I'm from phone and can't link it now), the message instead is taken from
the variables not incremented, right? Sorry if it's not very clear what I
mean, in which case I'll post a better answer when I get to a pc.
Il 06/giu/2014 19:22 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by liordon** [comment]
sorry to bring this up again, but do you have any ideas about the drop bug? It's been a long time since we discussed it but it still shows up on every egg drop. And these words do appear in the transifex, so it seems they just aren't used in some way or another.
![capture](https://cloud.githubusercontent.com/assets/4543336/3544879/89446734-0871-11e4-81df-ae11a6926778.PNG)

**Comment by deilann** [comment]
Is it just eggs? That's curious.

Sorry this isn't getting top attention. :/ I know it's frustrating and...
not that pretty.

**Comment by paglias** [comment]
It's just eggs only because it's one of the few strings rendered from the
server, where, for some reason I completely don't understand translations
use random languages. I'm really sorry but I have absolutely no idea why or
how this is happening, I've spent a lot of time trying to debug this
without success. One idea to hide the bug would be to use client side
translations for drops. I'll try in the next few days (I'll have access to
low/only mobile connection for about three weeks.)
Il 14/lug/2014 21:30 "deilann" notifications@github.com ha scritto:

> Is it just eggs? That's curious.
> 
> Sorry this isn't getting top attention. :/ I know it's frustrating and...
> not that pretty.
>

**Comment by deilann** [comment]
No, no worries. I don't understand translations at all. That's @paglias. I
just thought that potions would also do something similar, which is why it
was strange that it would just be eggs to me.

On Mon, Jul 14, 2014 at 12:56 PM, Matteo Pagliazzi <notifications@github.com

**Comment by Alys** [comment]
@paglias @deilann It is both eggs and hatching potions - see https://github.com/HabitRPG/habitrpg/issues/3802

I'm reopening this since it seems to not be fixed. I hope that's okay.

**Comment by paglias** [comment]
I'm happy to say that after a few months this specific issue should be finally fixed https://github.com/HabitRPG/habitrpg/commit/a30ee4368a4f525284f4f9ece1472de21d542909

**Comment by liordon** [comment]
I think this bug has recurred somehow, saw this just a moment ago upon feeding my pet. again, seems to be a variable name instead of the proper string.

![image](https://cloud.githubusercontent.com/assets/4543336/4817851/261b5924-5eed-11e4-8142-4ff78ac7b9f4.png)
