### ISSUE TITLE
clicks won't respond

### ISSUE THREAD

**Issue by mattrozak** [HabitRPG/habitica#427]
Over the past few days this issue has been pretty bad for me.  Sometimes when I load the page, clicking on checkboxes, +'s, -'s, and coin buttons does nothing.  I'll reload the page and try again until success. Sometimes takes up to four refreshes.

Chrome 24.0.1312.57 on OSX 10.8

sorry if this issue is already up, i couldn't find anything that looked the same after a cursory search.

**Comment by gerovac** [comment]
Same issue here, also Chrome 24.0.1312.57 / OSX 10.8

**Comment by lefnire** [comment]
can either of you tell me if there are javascript errors showing in Chrome
Console or Firebug when you click + - ?

**Comment by mattrozak** [comment]
first time i experienced a click not responding:

![Screen Shot 2013-02-18 at 5 36 54 PM](https://f.cloud.github.com/assets/1066386/169369/e0a95bc8-7a1b-11e2-8c2b-354ef84bdc8f.png)

second refresh, click did respond, no exception but the initial 403 error was still there.

third refresh, click did not respond with following error

![Screen Shot 2013-02-18 at 5 37 48 PM](https://f.cloud.github.com/assets/1066386/169370/e45e0e8a-7a1b-11e2-985f-9ad01e4a7e2d.png)

**Comment by lefnire** [comment]
Brilliant, that gives me something to work with - thanks Matthew

**Comment by kwilson328** [comment]
Confirmed for Chrome 24.0.1312.57 / OSX 10.7.5
However, my console only shows the 403 error, no others show up when I click.
And refreshing multiple times doesn't resolve it for me either.

**Comment by Pandoro** [comment]
I can confirm this as well. In some cases I need to refresh several times to do anything at all. Including making habits, todos, deleting them, checking things off. 

(Ubuntu 12.04 FF)

**Comment by mattrozak** [comment]
issue was pretty bad on chrome this morning so i hopped over to Firefox 19 - same deal. 

i've noticed that if i can click before the page stops loading (chrome stops "spinning") it will usually register, but that's usually only a few second time window.

**Comment by Pandoro** [comment]
I can confirm what @mattrozak  says, the site seems more responsive while it is still loading. After that it is pretty unlikely anything will work :x

**Comment by lefnire** [comment]
Oh goodness. Ok, today's task :)

**Comment by toebu** [comment]
I can reproduce this on my local copy (latest develop branch). This is definitely the same problem as #433.

I commented out line 22 in rewards.html to get rid of the 403 mentioned in #433 (for /img/BrowserQuest/habitrpg_mods/).
However, everything is still completely unresponsive. Everything as in: adding tasks, editing, deleting, buying rewards, all doesn't work. The only thing that works is opening the profile when clicking on the avatar. The clicks seem to cause no exchange with the server at all, no data is sent over the socket.

Firbug shows the following error when loading the page:

```
Error: Server and client page renders do not match
}
?play=.../onload (line 3218)
```

Also interesting: after loading the page for the first time, I experienced #417. I lost health for uncompleted dailys, then directly clicked on a daily to complete it, which restored my health to full. This was the last thing that ever worked. Since then I couldn't click anything anymore (even after reloading the page, logging out and back in and restarting the server).

I use FF 18.0.2 on Ubuntu.

Tested on Chromium (Version 24.0.1312.56 Ubuntu 12.10) and there it seems to work much more stable. The problem also happens sometimes but much less often.

**Comment by lefnire** [comment]
Ok, I'm gonna crack into this. @toebu you seem to have a pretty solid grasp of the code, so if you spot anything suspicious hit me up. Brb

**Comment by LittleFishChan** [comment]
I've noticed the same thing. It might respond for ONE click per every three or four refreshes, but that's it. Also, none of my habits (Non-checkboxes) are responding.

**Comment by toebu** [comment]
Tried to look through the last commits to find out what might be the problem, but didn't see anything obvious.
I have to run away now, good luck fixing this quickly!

**Comment by lefnire** [comment]
Could y'all give that a go and tell me if it fixed anything?

**Comment by lefnire** [comment]
btw @switz, I think this may be related to our 'validator' bug. I can get _this_ ticket to replicate as intermittently as our 'validator' ticket on local. I think I fixed the latter with https://github.com/lefnire/derby-auth/commit/17ec46fea4db0e615b78fa210549691397e2d4d3, gonna play more

**Comment by Pandoro** [comment]
Sadly for me it is still the same :x Tested by trying to check some
dailies, edit some todos and click some habits. Nothing works once the site
is finished loading. That is the dailies are getting checked, but no points
are assigned to me.

**Comment by lefnire** [comment]
ok, i've got it replicating consistently on local now. I'll play around. It's strange it's only for some people, works fine on my account - and lots of people playing today. Brb.

**Comment by lefnire** [comment]
and now?

**Comment by kwilson328** [comment]
Oh dear, I cleared all browsing history, cache, and cookies and then rebooted Chrome, and now Habit can't find my account! Guess I can't be of much help for testing the bug :(
![Screen Shot 2013-02-19 at 12 03 09 PM](https://f.cloud.github.com/assets/3534975/172801/10f8d1ae-7ac7-11e2-9b10-a43f71ac4fde.png)

**Comment by lefnire** [comment]
[email me](mailto:tylerrenelle@gmail.com) your username, email, or user-id - let me try to pull you up

**Comment by lefnire** [comment]
interesting, user with id `kwilson328` looks pretty solid in the database. try again?

**Comment by kwilson328** [comment]
Turns out it was user error. Have to login with username and not email address. Not sure it was always this way though.

Logged in successfully, click issue stil prevalent. Still able to get a few clicks in before server is done loading.

**Comment by ianjohnsa** [comment]
I am also experiencing this issue on Chrome Version 24.0.1312.57 m and Windows 7. Let me know if I can help testing anything (user name is 'ianjohnsa').

**Comment by derekantrican** [comment]
Same issue here. user name: derekantrican . User ID: 42f5dbca-a552-47aa-b038-c8df30596e7b Using both latest versions of chrome and firefox and windows 7 for both (same issue, no matter what).

**Comment by dbueller** [comment]
It isn't responding to my clicks either.  Also, when I try to rearrange a list, I get the following:

![Error](https://f.cloud.github.com/assets/3386878/173516/7bef9c46-7adf-11e2-8bd8-8ab58ec6b5d2.jpg)

**Comment by lefnire** [comment]
Any change?

**Comment by derekantrican** [comment]
Works for me now! Any way I could get back the 4 or 5 HP that I lost
because I wasn't able to click?

**Comment by dbueller** [comment]
It still isn't working for me.

**Comment by derekantrican** [comment]
Yeah, I take that back. It worked for a little bit, but now it doesn't anymore

**Comment by lefnire** [comment]
round 3 (sorry guys, it's so intermittently replicable - and we're still working on a proper test suite - that I have to keep trying ideas)

**Comment by derekantrican** [comment]
Works for me (so far). We'll see if it stays that way...

**Comment by lefnire** [comment]
Famous last words, but I think that last commit might have pegged it

**Comment by ianjohnsa** [comment]
Working for me now as well. Tried on chrome for Android and Chrome on Win 7.

**Comment by dbueller** [comment]
I can also confirm that it looks like it is working fine now.

**Comment by l--l** [comment]
This issue is now resolved for me, but I can no longer drap and drop my tasks to sort them within columns.

Chrome 24.0.1312.57 on Mac OS 10.8.2.

**Comment by lefnire** [comment]
Not much solace, but that's been an issue besides. Still working on that

**Comment by kwilson328** [comment]
Confirmed - issue resolved for me as well. 
Chrome 24.0.1312.57 / OSX 10.7.5

**Comment by lefnire** [comment]
awesome, awesome. Everyone who wants me to restore them to something, [email me](mailto:tylerrenelle@gmail.com) your user id and what stats you want back (50hp, 30xp, lvl3, gold arrmor, blue sword, etc)

**Comment by toebu** [comment]
Well done for finding it, just out of curiosity, which of your commits fixed it?

**Comment by lefnire** [comment]
this fixed it: https://github.com/lefnire/habitrpg/commit/223355fecb0776e994383eb6d108582de404e18b , and here's the comments why: https://github.com/lefnire/habitrpg/commit/66a7716b4a182054fee3dce6f439de3a9f0f7ed1

**Comment by justuswilhelm** [comment]
I still have the same symptoms. When I try to create new elements or click on existing ones the UI does not react and often I am forced to reload the page to make it work again. This pretty much makes the site unusable.

**Comment by lefnire** [comment]
@justuswilhelm can you try on beta.habitrpg.com?

**Comment by litenull** [comment]
The problem is persisting on beta.

On Thu, Apr 4, 2013 at 11:17 PM, Tyler Renelle notifications@github.comwrote:

> @justuswilhelm https://github.com/justuswilhelm can you try on
> beta.habitrpg.com?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/427#issuecomment-15924550
> .

## 

LP, Toma¾ :)

**Comment by litenull** [comment]
There's a message:
Client timed out; asking for snapshot!

**Comment by dt-rush** [comment]
This is still happening... on Android latest
