### ISSUE TITLE
Bug: I don't see party members

### ISSUE THREAD

**Issue by ra100** [HabitRPG/habitica#453]
I've created party and invited friend, she accepted and she sees my avatar, but I can't see her anywhere as a member of my party. When I try to add her again, I get message, that user is already invited or member of that party.

**Comment by ra100** [comment]
I accidentaly closed this issue :(

**Comment by lefnire** [comment]
I know what's wrong, will revisit when I get the chance. `model.push("parties.#{partyId}.members", newMemberId)` wasn't executing at all (or at least the callback wasn't executing), so I switched to a `model.fetch` with a manipulation of the array inside the callback, and saving it back to the db: [code here](https://github.com/lefnire/habitrpg/blob/develop/src/app/party.coffee#L139). For one reason or another this takes _forever_, and the invitee has to sit without refreshing her browser after clicking "Accept" until the page refreshes by itself. Will fix this.

**Comment by ra100** [comment]
I think I got to even more bugged state. I wanted to leave group, creat new one and invite people back :) but
scenario: M (me), U1 (user one), U2 (user two)
M creates party, invites U1. U1 accepts, U1 sees M, M doesn't see U1. M invites U2, U2 accepts, M sees only U1 (or U2, dunno, I forgot to check).
U1 leaves party, M sees nobody. M leaves party. M creates party. M invies U1 - error message, that she already is in party. M leaves party. U1 creates party, U1 invites M. M doesn't see request/invitation. U1 sees M in her party. 
I am confused :(
Is it possible to get out of this state, to leave all out groups, and start again with joining one party?

**Comment by lefnire** [comment]
working on issues here now, checking into @tsouthcotte can't invite another user

**Comment by lefnire** [comment]
Ok, I made some party-bug fixes. @ra100 can you check if your scenario still happens?

**Comment by tsouthcotte** [comment]
That worked for me, I can now see my friend in the group. Thanks!

**Comment by ra100** [comment]
Great, it works. Thanks @lefnire

**Comment by Pandoro** [comment]
Considering this has been fixed for two users I will close it. If anyone comes across the same issue, please post here, or open a new issue. 

Someone will reopen it if necessary :)

**Comment by C0000kie** [comment]
I had the same problem. I added a friend to the party (and they accepted). They show up in the browser, but I can't see them on the phone app. Then I reinstalled the app, but that only caused my other party members to disappear as well.

**Comment by C0000kie** [comment]
I am still not able to see my party member :(. Need some help

**Comment by Alys** [comment]
@C0000kie Can you please ask about that in the Report a Bug guild? It's within Habitica so we can see your Habitica account there which lets us examine it to find any problems that might be in it, although this is probably just from the app showing you cached data. You can reach the Report a Bug guild from the Help menu on the website or the Guilds menu item on the mobile app (you'll find it in the "Public Guilds" section). When you post there, tell us if you're using the iOS or Android app. We use GitHub only for issues that need code changes, and most bug reports don't need that, so posting to the guild is best.

**Comment by C0000kie** [comment]
Oh okay, thanks :)
