### ISSUE TITLE
To Do List Order Keeps Resetting and Tasks Reappear After Being Completed

### ISSUE THREAD

**Issue by NeepyNorp** [HabitRPG/habitica#4636]
Every time my screen refreshes, my tasks return to a particular order even after I put them in the order I want them to stay in. Also, after clicking off to dos, they sometimes reappear (usually as orange tasks regardless of the color the task was originally). Sometimes, this has even resulted in my tasks being duplicated as well.

**Comment by lemoness** [comment]
For the sort order, try clearing your Completed To-Dos! One of the
programmers will be able to help you with the duplicating tasks.

**Comment by Alys** [comment]
@NeepyNorp I'll look into your tasks reappearing and duplicating on the weekend (about 24 to 30 hours from now), if no one else gets to it first.

**Comment by kcunning** [comment]
I've noticed this as well. I'm on the latest Safari.

**Comment by Alys** [comment]
@NeepyNorp @kcunning If you're still having trouble with duplicated tasks or with tasks reappearing after you completed them, please give me your User IDs. If you're not sure what they are, [step 6 here](https://github.com/HabitRPG/habitrpg/issues/2760) shows you how to find them.

**Comment by NeepyNorp** [comment]
It looks like the issues have been fixed! Thank you!

**Comment by Leothil** [comment]
I still have the problem of my tasks rearranging themselves. This happens both on the full site and on mobile. Rearranging the tasks on mobile doesn't work at all; even when I clearly am dragging a particular task, it's always another one that ends up changing place. It's like the app chooses a task some centimeters above the one I tap and drag, to actually apply the change to.

**Comment by Alys** [comment]
@Leothil please see @lemoness's message above about that. If you'd like more information, see "Rearranging To-Dos" and the sections it refers to in the wiki's [To-Dos](http://habitrpg.wikia.com/wiki/To-Dos#Rearranging_To-Dos) page.
