### ISSUE TITLE
Public Guilds Menu Empty in iPhone and Android Apps

### ISSUE THREAD

**Issue by TetoIsGreat** [HabitRPG/habitica#4667]
A new user mentioned that the Public Guilds menu is empty on the Android App.  I went to check and it is empty on the iPhone app as well.  I feel like this bug was resolved, but might have been reintroduced in yesterday's iPhone update.  I am using the latest version of the iPhone App (0.0.48).  I was unable to find the original issue ticket.

ddb68b6c-296a-4dd2-abaf-dd1f562ac140

**Comment by deilann** [comment]
We're getting a lot of comments about this in the Tavern. @negue Do you know if this will be fixed soon?

**Comment by crookedneighbor** [comment]
I believe it is fixed, but I'm unsure if the update for the iOS store was submitted yet or not.

**Comment by deilann** [comment]
I still can't see the public guilds list of guilds I am not already a
member of on Android.

**Comment by crookedneighbor** [comment]
Good to know. Thanks!

**Comment by negue** [comment]
Looking at the code seems that my plan to get a faster app is now again stopped by duplicated ID error, this time guilds with the same id? how is that possible :/ Thats why it works on my android / account without a problem, but how this sounds like, some accounts are part of guilds with the same id

**Comment by negue** [comment]
Fixed with https://github.com/HabitRPG/habitrpg-mobile/commit/c78b73dc6b39763125e5fd5088c7fd3163a7bc5d
