### ISSUE TITLE
Join button appearing in a guild I am a part of

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4798]
See image. I've been in this guild for around a month and a half, and it's just appeared today.

![bug report image](http://i.imgur.com/hJdSKRC.png)

**Comment by crookedneighbor** [comment]
@knittingfrenzy18 I just noticed that too! I'm working on it now.

For the devs interested, on development, wrapping the button in a div with `ng-if="group"` was enough to delay the `::isMember` check for the buttons until the group actually loaded. In production, the isMember function is returning false even when I remove the one-time-binding. Any ideas?

**Comment by crookedneighbor** [comment]
Relevant files:
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/group.jade#L20-L21
https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/groupsCtrl.js#L18-L22

**Comment by crookedneighbor** [comment]
Okay, looks like the problem is that on the guilds pages, the `members` attribute, which is just an array of ids, gets replaced with an array of simplified user objects, for the first 15 users. So the `isMemberOfGroup` function only works if your user is in that list of 15 users.

https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/src/controllers/groups.js#L27-L49

**Comment by stillsnowedin** [comment]
@crookedneighbor Mind if I take a crack at this one? I have an idea for limiting the members list by their last login date rather than an arbitrary number. That way it's guaranteed to include the current user, but still won't have to load the entire list. It also has the added benefit of showing active users instead of random names.

**Comment by crookedneighbor** [comment]
Brilliant! Yes, please take it!

**Comment by deilann** [comment]
That could still be really, really taxing on the servers for large guilds,
like The Scholars and Challenge... Accepted?. If you do do that, it should
show 15 members and then you can choose to show more... otherwise it could
get very unwieldy and expensive very quickly to look up all those display
names.

**Comment by crookedneighbor** [comment]
@stillsnowedin Re-reading your comment after @deilann chimed in. I thought what you said was that you'd still limit it to 15, just show the 15 most recent users that have logged in. I agree with deilann that it still needs to be limited.

One obvious way around this would be be sure to include the current user in that list if the user is a member of the guild. Though, that's easier said then done.

**Comment by stillsnowedin** [comment]
"be sure to include the current user in that list if the user is a member of the guild"
That's tricky bit. We want the members list to show <= 15 members AND one of them has to be the current user (if they've joined the guild). I'm trying to figure out how to retrieve that from the server in one query, but haven't found the magic combination yet.

**Comment by Alys** [comment]
This should have been fixed by https://github.com/HabitRPG/habitrpg/issues/4908 which will go live in a day or two. We can reopen if that's not the case.

**Comment by Alys** [comment]
The fix I mentioned above had to be reverted, but this same issue was reported earlier in https://github.com/HabitRPG/habitrpg/issues/4427 so I'm going to leave this one closed. @stillsnowedin if you're still interested in working on this, would you like to comment in that issue?

**Comment by hairlessbear** [comment]
@Alys @crookedneighbor This issue is back, with a twist! The leave button is displaying, but so is the join button. 
![selection_004](https://cloud.githubusercontent.com/assets/7059890/8386403/ff3a96e6-1c1d-11e5-89ea-85b5ef494cfd.jpg)

This doesn't happen consistently; it's actually pretty uncommon, and I can't intentionally reproduce it. I find the issue interesting though, because on a surface level, it looks like `isMemberOfGroup` is [returning true and false for the same query](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/group.jade#L21-24).

**Comment by ghost** [comment]
@hairlessbear I believe the bug can be reproduced if entering the guild with url rather than from UI, but I'm not sure

**Comment by hairlessbear** [comment]
Just tried it with a couple guilds, and it didn't work. Thanks for the suggestion though.

**Comment by ghost** [comment]
@hairlessbear it does seem to work for me in the following order:
- join a guild, copy its url e.g. `https://habitrpg.com/#/options/groups/guilds/0cb00017-4074-435d-8b6d-717fabd7d492`,
- post a link in a chat of another guild e.g. `[no sugar guild](https://habitrpg.com/#/options/groups/guilds/0cb00017-4074-435d-8b6d-717fabd7d492)` in `https://habitrpg.com/#/options/groups/guilds/0cb00017-4074-435d-8b6d-717fabd7d492`
- open the link and see 2 buttons

**UPD**: or else may it be something to do with the state of _having just joined_ the guild?

**UPD2**: yeah, after some minutes / times entering the guild with the link the bug disappears for me

**Comment by crookedneighbor** [comment]
I've been noticing that intermittently too. It's definitely not related to just joining the guild, I see it on Aspiring Coders (of which I'm the guild leader).

**Comment by hairlessbear** [comment]
And as indicated in the screenshot above, it happens to me in Wizards of the Wiki, of which I've been a member for a while.

@crookedneighbor Any ideas of what could be causing this? As I mentioned above, it appears that the same query is returning true and false, but that seems impossible, so I'm assuming something else is happening...?

**Comment by crookedneighbor** [comment]
Not sure, will have to look at it. Might have something to do with a one-time binding.
