### ISSUE TITLE
Subscription renewal hourglasses

### ISSUE THREAD

**Issue by ericbaum** [HabitRPG/habitica#4819]
Hello,

I subscribed for 3 months consecutive, the time finished and paypal automatically renewed the subscription for more 3 months. 
But with the renewal I didn't get a hourglass for the 3 new months.

UUID: ac18def4-67c9-4d8c-9785-80914dbeb5c4

Thank you
##

**Comment by Alys** [comment]
@lefnire As I understand it, when a three-month repeating subscription is first started, the player receives one hourglass straight away. But it looks like they don't get a second hourglass when the automatic renewal happens. Are they supposed to? I would think that they are but I'd want to be sure before considering this as a bug (rather than feature we don't understand properly).

**Comment by lemoness** [comment]
Yes, they definitely should, since they've paid for another three months.

**Comment by ericbaum** [comment]
I imagined that I should receive it with the automatic renewal, because if I canceled the automatic subscription and subscribed again for 3 months then I would receive it.
If the requisite for receiving a hourglass is 3 months of consecutive subscription, it should happen no matter how that period is acquired.

**Comment by deilann** [comment]
Baum, I don't think anyone is saying you shouldn't get it -- what people
are asking is if there's another mechanism for when you'd get it -- say,
when the first rolls over and if that's the way it was implemented.
(Recurring subscriptions have their consecutive months updated on the
first, regardless of when they subscribed. So it might be like that.)

**Comment by ericbaum** [comment]
Yeah, I know, sorry if I sounded rude on the last post.

**Comment by deilann** [comment]
I just wanted to make sure you didn't think we were saying you shouldn't
get one! You clearly deserve it. :) We just need to figure out the
mechanisms that were put in place.

Thank you so much for being a subscriber and working through this with us.
<3 I'm gonna throw you a few extra gems for your patience.

**Comment by ericbaum** [comment]
Thank you! =]

**Comment by iamnotabanana** [comment]
Hello, 

I have the same problem.

User ID: 138cab15-a063-4a69-9e25-2ae73fc97a98

The habitrpg wikia says that you should get the mystic hourglass immediately after purchase (unless you only subscribe to one month at a time). It doesn't make much sense otherwise.
http://habitrpg.wikia.com/wiki/Mystic_Hourglass

**Comment by FoxWhiskers** [comment]
Hello! So my 3 month subscription just renewed too, and I also do not have the hourglass, plus, I do not have raised gem cap (since this is the second round of 3 months, im guessing it should be at 35 now?) does this mean i wont get the 5 extra this month?

**Comment by lefnire** [comment]
Indeed, the current mechanic is: it applies advance consecutive counters
only on first checkout, and subsequent consecutive counters act as if
you're month-to-month. As pointed out in this thread, that's incorrect - an
oversight on my part, apologies. I can't look into it just yet, hopefully
in coming days - anyone handy?

**Comment by Crystal00** [comment]
It looks like this is still an issue? I had an automatic renewal on May 20th and still no mystic hourglass. 

User ID 251a1749-8407-4307-91fc-6d30f5af319b

Thank you

**Comment by Alys** [comment]
@Crystal00 Sorry about that! I've given you an extra hourglass and increased your monthly gem cap by five. If you don't have the gold saved up for the extra five gems this month, you can go to Settings -> Site -> Fix Character Values to give yourself a loan.

**Comment by Alys** [comment]
@ericbaum @iamnotabanana @FoxWhiskers I can't tell from the comments here if your problems were fixed. Please post again if they were not. @ericbaum we'd need your User ID from Settings -> API.

**Comment by ericbaum** [comment]
No, the problem is still up. I haven't received that old hourglass yet.
But I'll just be able to see if it is working with auto renewal next month =]

UUID: ac18def4-67c9-4d8c-9785-80914dbeb5c4

**Comment by Alys** [comment]
@ericbaum Sorry about that! I've given you the trinket that you should have received in March, and increased your monthly gem cap, and given you the extra gems you would have been able to buy in March and April had the gem cap been increased then as it should have. If you don't have the gold saved up for the extra five gems this month, you can go to Settings -> Site -> Fix Character Values to give yourself a loan. You should receive a new trinket and a higher gem cap with the next auto renewal. Post here if any of that hasn't worked.

**Comment by Crystal00** [comment]
@Alys Thank you very much for the quick reply and fix. Thanks for the extra
gems as well!

**Comment by ericbaum** [comment]
@Alys Ok. Thanks a lot =] I'll let you know if anything goes wrong.

**Comment by AstroKicker** [comment]
Hello! My account was renewed on May 16. I didn't receive a mystic hourglass. I think my gem caps was raised by 5 though? Is 20 the cap?

My user ID: b4b9dfad-b624-44b0-94b1-e6e47a28b1a1

Thank you!

**Comment by hairlessbear** [comment]
@AstroKicker Have you subscribed for three months consecutively?

**Comment by AstroKicker** [comment]
Yes, this is my 2nd round @ $15.00

**Comment by hairlessbear** [comment]
Sweet, just double-checking. I'm not an admin, so you'll have to wait for one of them to pop by to get real help. Thanks for subscribing!

**Comment by Alys** [comment]
@AstroKicker You should now have one new Hourglass and an extra 5 gems on your monthly cap (the base is 25). Tell us if it hasn't worked! You might need to sync or reload to see the changes.

**Comment by AstroKicker** [comment]
Thank you Alys & hairlessbear  ;)

**Comment by Lenyberry** [comment]
I"m also having this problem. I subscribed for the 3-month recurring stripe, and everything went as it should the first round. My card was charged for the second time on June 15 and I received a confirmation email about the payment and renewal of my subscription, when I didn't see the additional hourglass / gem cap I figured maybe that rolled over on the first of the month so I waited to see what would happen, but I still don't have either.  

In case this helps at all, if I click the gem icon at the top to see subscription information it shows: 
Consecutive Months: 4
Gem Cap Extra: 5
Mystic Hourglasses: 0

User ID: c63c53b8-c516-4836-857a-eef9329c597c

**Comment by Alys** [comment]
@Lenyberry Sorry about that! I've fixed it for you. You should now have an hourglass and an extra 5 gems on your monthly cap. Please reload if you don't see the changes.

**Comment by jaredoOS** [comment]
Just ticked over my 3 month renewal a couple of days ago and didn't get a second hourglass, I hadn't used my original one so I used that to see if that would kick it over but no luck. My initial subs all was as expected. 
Everything else seems in order, except I didn't double check my Gem count before I'd bought a few. 

User ID: 1e1db840-bd6c-41df-94bb-673247f084ee

Payment went through on the 27th June.

**Comment by Alys** [comment]
@jaredosborne Sorry that bug hit you! You should now have an hourglass and an extra 5 gems on your monthly cap. Please reload if you don't see the changes.

**Comment by janetmango** [comment]
Same thing with  my recurring 6-month subscription, payment made via PayPal on 6/25/2015. UserID is d075dca7-01ed-4666-ae2d-22feef18c7bc.  It incremented my consecutive months by 1, but didn't get gem cap increase or Mystic Hourglasses.

**Comment by Alys** [comment]
@janetmango From what I can see, everything is correct with your account. Your subscription started on 2014-07-25T12:07:04.620Z which means you've had a total of three full 3-month consecutive periods (you'll finish the fourth period on 2015-07-25). You get one hourglass and a gem cap increase for every full 3-months you are subscribed, so you've had three hourglasses and three increases so far and it looks like they've all been applied correctly. Your next hourglass and increase is due when the next three month period is finished, around 2015-07-25.

If you think that's not correct, please tell me the email address you use with PayPal. You can PM it to me if you don't want to paste it here. Note that even if there was a payment on on 6/25/2015, that doesn't necessarily mean that a 3-month period ended then. If your first few months were not on the 6-month plan that you're on now, then your PayPal payments won't match up with your blocks of consecutive 3-month subscriptions.

**Comment by janetmango** [comment]
@Alys When I converted my recurring 1-month subscription to a recurring 6-month subscription, I got my 2 Mystic Hourglasses, 10 gem cap increase, and 6 months added to my consecutive month counter at the time I purchased the 6-month subscription. Does this only happen for the first purchase and doesn't happen again when the recurring block payment is made? I will PM you my PayPal account if it will help.

**Comment by jaredoOS** [comment]
Thanks @Alys!

**Comment by Alys** [comment]
@janetmango Sorry about the delay. You actually used a different email address with PayPal so it took me a while to find your details. You did make a new 6 month subscription payment so I've increased your hourglasses and cap.

**Comment by intirb** [comment]
Hi - I'm having the same issue.  I've been subscribed for 5 consecutive months now, but I never received my second hourglass.

UID: fcbeedbb-d4f9-4eca-bfc9-6e32a6f172a1

Consecutive Subscription

```
Consecutive Months: 5
Gem Cap Extra: 5
Mystic Hourglasses: 0
```

Thanks!

**Comment by Alys** [comment]
@intirb I've fixed that for you. Let me know if there's still problems!

**Comment by xSwitchx** [comment]
I also seem to be having this issue with both the gem cap increase and the hourglass.

UID: a46cd5c2-8f69-4a4a-9b96-e29f8e2e3262

Consecutive Conscription

Consecutive Months: 4
Gem Cap Extra: 5
Mystic Hourglasses: 0

Thanks.

**Comment by Alys** [comment]
@xSwitchx I've fixed that for you.

**Comment by xSwitchx** [comment]
@Alys Thank you!!!

**Comment by MrPaHabitica** [comment]
Hello! I just had the bug too. My subscription was renewed, but I didn't get any Hourglass.

My UID is 82a5cc1f-5e25-455a-b7d3-05a4d1ee3c9e

Thanks in advance!

**Comment by rezolv** [comment]
I think I may have had the issue for awhile

UID: 2d3c86ab-9469-4895-971a-f50d2e3470f2

 Consecutive Subscription
Consecutive Months: 15
Gem Cap Extra: 25
Mystic Hourglasses: 0

**Comment by Alys** [comment]
@MrPaHabitica I'm sorry about the delay! I missed your comment when you first made it. I've fixed that for you now.

@rezolv When this bug occurs, it happens when a block subscription is renewed (not when it's first created), and the effect is that **none** of the benefits of a consecutive subscription are applied (i.e., you don't get the hourglasses or the increased gem cap). It doesn't look as if that's what's happened with your account. I haven't investigated in depth, but from what I have seen, everything looks normal. Can you please check your subscription details and if you think anything is wrong, please post again here and describe the problem.

**Comment by rezolv** [comment]
@Alys Well I could be wrong, but I noticed that I had not gotten hourglasses in a while and have only gotten them twice since I started my block subscription. Once at the beginning and then maybe again at 6mos. Please let me know if there is other information I should provide.

**Comment by MrPaHabitica** [comment]
Thanks a lot Alys!

**Comment by Alys** [comment]
@rezolv You purchased a 12 month subscription on 2014-12-17. That means that one payment has been taken for it (at the start of the subscription), and it hasn't been renewed yet. Hence you'd expect to have been given four Hourglasses, on one occasion only, on 2014-12-17 when the subscription started. You shouldn't (and wouldn't) have been given any more after 6 months.

In addition, you had earlier subscription payment(s) that started on 2014-08-25 and might or might not have been consecutive until your yearly subscription started. If you want me to check on that, please email the receipts to admin@habitica.com or email that address to state which payment method was used and which email address was associated with that payment method. If we assume a three-month consecutive period before 2014-12-17, then you would have been given additional Hourglass for that period. So you should have had five Hourglasses in total.

Your equipment list shows that you have all of the Mystery Items for all months between 2014-08 and now (i.e., from when your first subscription started). You also have five additional sets of Mystery Items: 2014-02, 2014-05, 2014-07, 3014-04, and 3014-05, which accounts for the five Hourglasses you had been given.

If you still think you have not been given the correct number of Hourglasses, please email us the details of your earlier subscription.

**Comment by jaredoOS** [comment]
Hi guys, I had this 3 month problem when I first signed up, still seems to be continuing. Now (subs for 7 months) I didn't get my Mystic Hourglass for the last renewal a month ago. Am fairly sure the gem cap went up fine. 

User ID: 1e1db840-bd6c-41df-94bb-673247f084ee

**Comment by Alys** [comment]
@jaredosborne Typically when this bug happens, neither the Hourglass nor the increased gem cap are received, and it only happens at the end of the first period. Your subscription started on 2015-03-27 (GMT) so you should have been given three Hourglasses in total. You have no Hourglasses at the moment, but you do have the Mystery Items for 201407 and 301405 (in addition to the Mystery Items for the months in which you were subscribed), and you have the Mammoth pet which you would have obtained with an Hourglass since your Habitica account was created after the pet was awarded to all players. Let me know if you don't see any of those items in your account - there might be a bug that is preventing them from being visible.

**Comment by jaredoOS** [comment]
ah, i forgot the mammoth was an hourglass thing. My bad, thank you :)

**Comment by rhymeswithsarah** [comment]
I'm also having a problem with hourglasses. At my most recent renewal (for three months), I didn't receive my mystic hourglass. And the mystic hourglass from the three-month renewal before that, I didn't use right away - and it disappeared when I took the Orb of Rebirth! So I'm missing two hourglasses now :( 

UID: 505fa139-f5ff-4447-92ac-7b9ea669f880

**Comment by Alys** [comment]
@rhymeswithsarah I'm looking into this for you. Can you tell us please approximately when you used the Orb?

**Comment by Alys** [comment]
@rhymeswithsarah You have a six-month subscription, not a three-month subscription. When it was started, six months ago, you would have been given two hourglasses then. I can see that you have Mystery Items for 2014-04 and 2014-08 (both from before your subscription started), so it looks like you did use both Hourglasses and you haven't lost any that you had been given (so you don't need to tell us when you used the Orb). I've given you the Hourglasses and gem cap increase that you should have been given at your first six-month renewal.

**Comment by janetmango** [comment]
I just paid my 6-month block subscription on 12/25/2015 but didn't receive my 2 Mystic Hourglasses.  However, I don't know if I'll need them since I have all the items from the Time Travelers shop already....???  Thanks in advance.

**Comment by Alys** [comment]
@janetmango Sorry about that! I've given you the Hourglasses.

**Comment by rezolv** [comment]
@alys Now it appears that it did happen with my recent 12 month renewal. UID: 2d3c86ab-9469-4895-971a-f50d2e3470f2

**Comment by Alys** [comment]
@rezolv Fixed. Please reload to see the Hourglasses.

**Comment by Sinead007** [comment]
Hi there, I am also having an issue with the auto-renew. My subscription renewed yesterday after 12 months and no hourglasses, also my gem cap did not go up by 5 (though I'm not sure if it should have?).
UID: 2301bd83-4384-4865-a31c-6a56e8e6af37
Thank you for the help!!

**Comment by Alys** [comment]
@Sinead007 Sorry about that! I've given you the Hourglasses and the increased gem cap - it was meant to go up to the maximum of 25 extra (50 gems per month in total). Reload if you don't see the changes now. Note that you should now be able to buy another 5 gems this month.

**Comment by Sinead007** [comment]
Everything looks great, thank you so so much for your time!!!

**Comment by jrenee25** [comment]
I'm also experiencing this issue:  I subscribed but have not yet gotten any additional hourglasses and my gem cap is stuck at 20.  Can you please assist?  My user ID is 37635d5f-c9cb-4842-8c86-2a0be1263afa.

Here's what it says on my subscription page:

Subscribed
Recurring $48 USD each 12 Month(s) (Paypal)
Consecutive Subscription
Consecutive Months: 12
Gem Cap Extra: 20
Mystic Hourglasses: 0

**Comment by Alys** [comment]
@jrenee25 From what I can see in your account and in PayPal, you created the twelve-month subscription only ten months ago, so it hasn't renewed yet. You get additional Hourglasses and an increased gem cap (to a maximum of 25) each time it renews. Comment here again if you don't see them after it has renewed.

**Comment by jrenee25** [comment]
So your are saying that if I just renewed each month (rather than paying for an annual subscription) that I would get an increased gem cap and a new hourglass every three months?  That stinks.  I thought paying it all a year in advance would give me the same (or more) perks than someone who pays month to month.

**Comment by Alys** [comment]
@jrenee25 When you buy a bulk subscription, you get all of the Hourglasses and increased gem cap immediately at the start of the subscription, so you did get the same perks as a month-to-month subscriber but straight away instead of waiting. Also, for the twelve-month subscription, you get a reduction in price compared to 12 one-month subscriptions.

You get additional Hourglasses and an increased gem cap (to a maximum of 25) each time it renews. Comment here again if you don't see them after it has renewed.

**Comment by jrenee25** [comment]
@Alys , my subscription renewed on May 20, 2016 05:00:41 PDT (Transaction ID: 7NG63989GR750834S) and I did not get any more hourglasses and my gem cap is still stuck at 20.  Please fix this.  If I am supporting Habatica, I would like to get the subscriber perks that were promised.

**Comment by Alys** [comment]
@jrenee25 As I mentioned, all you have to do is let us know when the problem occurs and we'll always fix it. You have your hourglasses and increased gem cap now.

**Comment by crookedneighbor** [comment]
@jrenee25 we figured out the source of the bug and deployed a fix a little after your subscription would have renewed. So, hopefully, this is the last time this will happen to you.

**Comment by jrenee25** [comment]
@Alys @crookedneighbor thank you both so much!  I'm excited to have my hourglasses and increased gem cap - time to go shopping!

**Comment by SabreCat** [comment]
We've gotten a couple more reports of this over the last week or so. Guess it's not quite done with us yet. :\

**Comment by reneamac** [comment]
Hi everyone. I've been a subscriber since... February, I think. In that time, I haven't gotten any Hourglasses except when first subscribing. My Gem Cap is still at 20 as well. Thanks for looking into this. 

862f595d-72a7-42fc-a1d0-324bbb139456

**Comment by Alys** [comment]
@reneamac You subscribed for a twelve-month recurring subscription in February, so you received all the benefits then and you're due to get your next Hourglasses next February (for details about subscription benefits, please see http://habitica.wikia.com/wiki/Subscription ). If the Hourglasses don't appear in February when your next payment is taken, you can go to Help > Report a Bug from the website's menu or Guilds > Report a Bug on the mobile app and report it there - that's a guild in Habitica so it's typically faster to post in and we can see some details of your account from there so we can troubleshoot most problems faster than through GitHub.

**Comment by reneamac** [comment]
Thanks, @Alys. That Wiki description is much more clear than the one in the Benefits pop-up. Thanks again.

**Comment by joe-salomon2** [comment]
@Alys, what's the status of this?

**Comment by Alys** [comment]
@joe-salomon These days when a 6 or 12 month subscription renews, the user gets 1 hourglass immediately and then after 3 months pass, they get the next. That behaviour is incorrect - they should receive all their hourglasses immediately (2 for the 6-month sub and 4 for the 12-month) and then should not get any more as the months pass.

The `purchased.plan.consecutive.offset` field in the user's account controls whether they get an hourglass as the months pass. For a 12-month subscription, when the subscription renews, what's supposed to happen is that 4 hourglasses (`trinkets` in the code) are added to the user and the offset is set to 12. Each month, cron's subscription checking code decreases  the offset  by 1, and increases `purchased.plan.consecutive.count` by 1. When count gets to a multiple of 3, the cron code checks to see if offset is zero. If it is zero, and hourglass is given.

I think what might be going wrong is that the number of hourglasses given when the subscription renews is incorrect and the offset is not being set. However I haven't looked at the code recently. 

Ask again here if you have more questions or if I've explained this badly.

**Comment by joe-salomon2** [comment]
Cool, I'll take a look

**Comment by MathWhiz** [comment]
@joe-salomon2 Are you still working on this?

**Comment by Alys** [comment]
I'm going to have a go at implementing my idea from https://github.com/HabitRPG/habitica/pull/8818#issuecomment-318834481 to see if it helps. I'm marking this as in progress for me.

**Comment by paglias** [comment]
@Alys has this been fixed?
