### ISSUE TITLE
Habits, to-dos and tags randomly multiplied

### ISSUE THREAD

**Issue by Siphike** [HabitRPG/habitica#5161]
I just logged back in and found all my tags had been cloned. I deleted all the cloned tags. Then I noticed the same thing had happened with my habits and to-dos - some of them are just there once, but others have up to 5 clones. Some of the tasks have kept their tags, while others have had them wiped. (No change to the dailies.)

Also, when I go to delete the extra tasks, the task whose trash can I've clicked on doesn't always seem to be the one that gets deleted. Any help appreciated. :)

(Side issue: I received about 80XP for no apparent reason. I only just signed up for HabitRPG yesterday and this was enough to level me up. I was looking forward to earning my level. Why did I receive those points?)

User ID: cbf1a898-da43-4263-ab63-2d9baa72e564

**Comment by hairlessbear** [comment]
This sounds like the same issue as #4470/#4773. In terms of deletion, as it says in #4773:

> you'll be able to delete the duplicates if you start from those at the bottom of the list, rather than at the top.

In terms of the extra XP, are you using a third-party extension (for example, the [HabitRPG chrome extension](https://chrome.google.com/webstore/detail/habitrpg/pidkmpibnnnhneohdgjclfdjpijggmjj?hl=en))? If so, that's likely where the XP came from. If not, I'm not sure about why you have extra :confused: However, if you'd like to undo it, you can manually revert your XP and level by using [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values).

**Comment by Siphike** [comment]
Thanks - that really helps. Much appreciated. :)

**Comment by hairlessbear** [comment]
Glad to help! Does that mean that your issue is solved? If so, could you please close the ticket?

**Comment by Siphike** [comment]
It's kind of solved. I know what I wanted to know - how to fix it when the bug happens - but the bug is still there. However, there's already a ticket open to address that issue.

**Comment by hairlessbear** [comment]
Got it, thanks for the clarification.

**Comment by CCapra** [comment]
This just happened to me too. Duplicate habits, dailies, to dos, and rewards. Even checked off dailies show up (duplicate greyed-out dailies, with checkmarks) It seems like all the duped ones were just created yesterday - older items aren't duped. I think I started using habitrpg on a second computer around the time they are duped after.

Some things are duped as much as 12 times. 

I'll delete from the bottom as recommended. But is there a fix?  I'm using win8.1 in each computer.
