### ISSUE TITLE
Unable to pay via Amazon Payments

### ISSUE THREAD

**Issue by alexiabowers** [HabitRPG/habitica#5655]
I tried to pay for my subscription via Amazon Payments, and got the attached error:
![screenshot 2015-07-22 11 30 05](https://cloud.githubusercontent.com/assets/4634418/8829561/4863b2e8-3065-11e5-9ab1-9c63efbb1375.png)

**Comment by Alys** [comment]
@alexiabowers I'm very sorry about this! Amazon are asking us for information about HabitRPG (which we believe we already gave them early in the process of setting up an integration with them!) and until we provide it, they've suspended the ability to make payments through them. redphoenix (@veeeeeee) is negotiating with them about this, and hopefully it won't be long now until it's fixed.

The other payment methods should work, although of course I understand that you might prefer to use Amazon. If you end up missing out on the July Mystery Item because of this problem, we can ensure that you do get that item when your subscription is set up.

**Comment by alexiabowers** [comment]
It didn't stop me from subscribing, I just went the direct credit card route. But I wanted to log the bug to make sure you knew about it.

**Comment by Alys** [comment]
:heart: :heart: Thank you for subscribing and for taking the time to tell us!

**Comment by veeeeeee** [comment]
I've pinged my contact at Amazon again to see if he's made any progress in figuring out what's going on. Thanks for letting us know and for the support!

**Comment by redmanatee** [comment]
I just attempted to purchase through Amazon as well, and I can state that it is still not working (for the same reasons the original bug has).  Note: Not complaining, not angry, just letting you know that it is still not fixed.

**Comment by paglias** [comment]
Should be fixed now

**Comment by grammarware** [comment]
Seems like this (or similar) bug is back: getting "Application Error" when trying to pay with Amazon.

**Comment by Alys** [comment]
@grammarware Could you please show us a screenshot of the error? Please also tell us your User ID and browser details - please see steps 6, 7, and 8 from the [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/5655) page.

**Comment by grammarware** [comment]
ID 89879218-ba50-47aa-b688-e163d0601c6f
Mac OS X 10.10.5 (14F27), tried in Chrome and Firefox, here's a screenshot from Chrome with the console:
<img width="1680" alt="screen shot 2015-09-20 at 15 08 26" src="https://cloud.githubusercontent.com/assets/1658264/9981052/fef6eb40-5fb0-11e5-9c65-97734ded7514.png">

**Comment by crookedneighbor** [comment]
If I had to guess, I'd say it was do to one of your chrome extensions. 

Would you mind disabling them and trying again?

**Comment by grammarware** [comment]
Already managed to get further from an Android phone (who would have guessed that at some point a mobile browser would work more reliably than a desktop?!), seems like payments directly from the Amazon account are not supported anyway (only from a credit card through Amazon), so the feature is not relevant for me any more. Thanks!
