### ISSUE TITLE
Party Invitation Persisting After Joining

### ISSUE THREAD

**Issue by kuestegg** [HabitRPG/habitica#5969]
I've joined the party I was invited to, yet I still have the invitation message appearing in the party screen.  I'm also showing as both a party member and invited on the left tab.  I've left the party and rejoined.  My leader also tried removing me, deleting the invitation, and having me rejoin.  The invitation is still persisting.

**Comment by Alys** [comment]
@kuestegg Can you please comment briefly on this issue: https://github.com/HabitRPG/habitrpg/issues/5649
and include your User ID? You can find out how to find your User ID by going to Help -> Report a Bug and referring to step 6. Unfortunately we can't help you without knowing your User ID, but once you tell us, we can remove the invitation.

**Comment by kuestegg** [comment]
Hi, thanks for following up!

My user id:  d64c0ace-a20c-47d3-9468-5a66049e8382
Our group id:   f2a9e3d8-8c36-40ec-bd8b-10cea56271cb

**Comment by Alys** [comment]
I've fixed this.

**Comment by kuestegg** [comment]
I'm still seeing the invitation, do I need to refresh anything on my end for the fix to complete?

**Comment by Alys** [comment]
I've deleted it again. Your browser (or possibly the browser of the person who sent the invitation) is probably storing the invitation and making it reappear. Log out of Habitica, clear your cache and cookies, and clear local storage for habitica.com (that's a different process than clearing cache - you might need to google for instructions for your browser).

**Comment by kuestegg** [comment]
Ahh that seems to have done it.  Thank you for your help!
