### ISSUE TITLE
Erratic HP behaviour linked to Todos not disappearing.

### ISSUE THREAD

**Issue by horusofoz** [HabitRPG/habitica#60]
Ticked a Todo and when it did not disappear I (curiously/foolishly) un-ticked it. Instantly my health emptied to NaN and the task went blank as per ticket #38. 

Being curious I ticked it again, no health restored, then un-ticked it. Instant death and saw the cool little Grim Reaper graphic for Game Over. 

Logged out and back in but still back at level 1.

**Comment by horusofoz** [comment]
This and #38 just wiped me out again.

Also now I have more blank todos than valid ones.

**Comment by lefnire** [comment]
see #84. Also, blank todos issue should be fixed now

**Comment by horusofoz** [comment]
Sadly still present after a refresh. Think I may need to reset and start again.

![Image 4](https://f.cloud.github.com/assets/3202339/70153/f9ade664-5f83-11e2-9850-1da07ee99260.png)

**Comment by horusofoz** [comment]
I'm guessing you just made a change as now I have no habits, dailys or todos. Not a huge issue but would have been good to get a screeny of my tasks first as I don't remember everything I had. If issue recurs will advise.

**Comment by lefnire** [comment]
sorry, db went terribly awry - i'm restoring from a snapshot of a few hours ago. I'm going to have to tackle this issue in the morning, i'm dyin' here

**Comment by horusofoz** [comment]
Thank you for the restore. Get some sleep. Nothing more important than
personal health. HabitRPG's road to world domination can wait until
tomorrow :)

_Horusofoz_
*
*
"Live to learn. Learn to live." J.W.S.

**Comment by lefnire** [comment]
give it a shot now

**Comment by horusofoz** [comment]
With the empty tasks gone as resolved under #38 this ticket can also be closed. Thanks.

**Comment by horusofoz** [comment]
Sad to say we have a recurrence of completed todos not disappearing. I haven't been willing to untick, tick to see if they go blank.

![Image 2](https://f.cloud.github.com/assets/3202339/82417/8d99d5f6-63a6-11e2-8fb0-f865a3bb93c3.png)

**Comment by FaeriMagic** [comment]
I don't know what happened, but my hRPG is completely blank. No HP (Shows NaN), No tasks, can't logout, can't do anything. It happened recently, about last night. 
![image](https://f.cloud.github.com/assets/3200203/91334/03d7cab6-659b-11e2-824f-e5dab4a47222.png)

**Comment by wc8** [comment]
@faerimagic Try clearing browser cache. Then refresh.
If that doesn't work, try deleting habitrpg cookie in browser settings. Then try refresh again and login if possible.

**Comment by lefnire** [comment]
holy god. faeri, email me your uuid i'll restore you from a previous backup: tylerrenelle at gmail

**Comment by lefnire** [comment]
(or if you can't access that, then your email or username you used to sign up)

**Comment by FaeriMagic** [comment]
Deleting the habitRPG cookie fixed the issue. Logged in and found everything as it was. Though it was a surprise when I found that my HP decreased by 21. Eh, oh well. At least it works again!
Thanks, wc8! 8D

**Comment by lefnire** [comment]
Phew!

**Comment by horusofoz** [comment]
Believe this is nor resolved. Haven't had any recurrences and no one else has reported any.
