### ISSUE TITLE
limited time purchasable items (e.g., Magic Hatching Potions, Grand Gala equipment) can't be bought at the end of the end of the event

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#6169]
_EDIT 2019-11-03: See https://github.com/HabitRPG/habitica/issues/6169#issuecomment-549111718 for the latest status. -- Alys_

_EDIT 2019-11-09: The comments just below that one for a method to replicate the bug and a suggested unconfirmed fix. -- Alys_

**EDIT 2020-01-09: The staff have approved the fix described in this comment: https://github.com/HabitRPG/habitica/issues/6169#issuecomment-552068039 -- Alys**

In the final day or so of any Grand Gala, some players find that when they buy the special class gear and other limited edition items, the items disappear after a sync.

I believe this is because of timezone conflicts between the user's browser and the Habitica server. If that's true, then we should be able to fix it by using the user's value of `preferences.timezoneOffset` (e.g., -600 for a user in the GMT+10 timezone). I.e., the code that decides whether to display the items in the rewards column should consider the user's timezone as well as the date range of the availability period so that the items are not visible to the user after the server knows that the date range is over.

The code should assume a zone of GMT (0) if the user doesn't have a value for timezoneOffset.

---
### What to do if this bug has happened to you:

**If you've purchased seasonal items and they have disappeared, please do NOT comment on this issue. This issue is only for discussing the code required for a permanent fix. To help us focus on a fix for this, we might delete any comments here that aren't directly related to fixing it.**

**Please describe your missing items on https://github.com/HabitRPG/habitrpg/issues/6644 and we'll give them back to you.**

**Comment by TheHollidayInn** [comment]
When you say the items disappear, do you mean they disappear from the user's inventory, the rewards column or the time shop? Or a mix?

Also, are you able to replicate this in any way?

**Comment by SabreCat** [comment]
@TheHollidayInn: They disappear from the Rewards column--or, even worse, they sometimes _don't_ immediately disappear from the Rewards column, but when you buy them, they vanish from inventory and refund the Gold upon next sync.

Replicating it should be possible, if a little tricky. This would do it:
1. Change the `event` date range of a seasonal set in the `content` file so that the item is active through the current date
2. Run your Habitica server using a time zone that's ahead of the one you'll connect to with your client
3. Log in with the above mismatched zones, and keep the app open across the divide where the server reaches a new day outside of the event date range 
4. Attempt to buy the seasonal items while the client is still on a day within the stated range of availability

Not all of that may be strictly necessary, but it's the most likely to reproduce the problem in its worst mode.

**Comment by SabreCat** [comment]
Does this still happen as described post v3? I might expect people to see error messages instead of rollbacks, at least.

**Comment by Alys** [comment]
Judging from the blissful absence of complaints this time, this seems to be fixed. :heart: :tada: :tanabata_tree:

**Comment by SabreCat** [comment]
@veeeeeee ran into this, or something very much resembling it, today. https://gyazo.com/fa6c6571c5953d6a0af1da17303b8466

It was 5:43 PM in the Pacific time zone when she reported it, which would mean it was February 2 in UTC but February 1 in her local zone. The `EVENTS` end date is `2017-02-02`...

**Comment by librarianmage** [comment]
Is this still an issue?

**Comment by Alys** [comment]
Yes, I'm pretty sure we had problems like this at the end of the most recent Grand Gala.

**Comment by lemoness** [comment]
Was this fixed with the Winter Wonderland gala?

**Comment by Alys** [comment]
It was certainly at least much less common. Closing. We can reopen next Gala if needed.

**Comment by Alys** [comment]
This is still happening. Below is feedback from Praxis / @Praxissima (0ce6d43b-efa2-45a3-acaa-59daad7d658d) about it (edited to highlight the most important parts for this issue), including confusing mixed messages that are given when you try to buy an item after it's no longer supposed to be available.

**Praxis**: "... I purchased [this season's outfit] from the seasonal shop. Yet when I equip them in my inventory there is a pop-up that says "You do not own this item" even while it is equipping it. The outfit looks fine in my avatar panel... and then when I re-load the page it is gone."

**Praxis**: "... I tried buying it yet again. This time it said "You can't buy this item" on the first click and "You already own this item" on the second click for each piece."

_**Alys**: "it looks like you tried to buy the equipment around 2019-11-02 06:30 UTC, so the problem was that it was no longer available for sale then - the official purchase period ended at the end of 31 October. The website might not have been reloaded recently so it might have still been showing you old data. ... Did you see any error messages while you were buying the equipment?"_

**Praxis**: "As for error messages, it was mixed: I would get a blue oval confirming that I had purchased the item, along with a red oval saying that I had spent some gold, and then I would get a bigger red oval saying "You can't buy that item."

**Praxis**: "I reload the site every day when I start my browser, if not more than once per day, so that should not have been an issue."

**Praxis**: "I think that this was more than simply a site loading issue, for another reason: When I changed classes, the gear that was available for my new class changed appropriately in at least four places: The Seasonal Shop display, the main Market page, my Equipment inventory, and the right-hand sidebar (Rewards column) of my Tasks page. Since everything was continually updating in response to my actions, and changing the items that displayed accordingly, it seems that this was more than an issue of needing to reload the site (and I did reload at least two or three times during the process of attempting to buy the seasonal items)."

This is worth fixing if we can because it can cause players to change class to buy gear and end up without the gear. Praxis spent 3 Gems to change class after buying the gear for the current class because it wasn't clear that the first purchase had failed.

I'm marking this suggestion-discussion so that we can consider how best to improve the situation.

**Comment by Alys** [comment]
I'm marking this suggestion-discussion so that we can consider how best to improve the situation.

**Comment by Alys** [comment]
By the way, this is worth fixing because it can cause players to change class to buy gear and end up without the gear. Praxis spent 3 Gems to change class after buying the gear for the current class because it wasn't clear that the first purchase had failed.

(sorry about the multi-email spam)

**Comment by Alys** [comment]
I've replicated this on my local install using two computers on my home network, with each one set to a different time zone. There's probably ways to replicate it using a single machine but this way was easiest for me.

1. Install Habitica locally on one computer - this is referred to as "the **first** computer" in the steps below. (If you already have Habitica installed on a computer, it's fine to use that one, it does not need to be a new install.)
2. Stop the local install's webserver if it's running (i.e., if you've already run `npm start` and `npm run client:dev`, stop both those processes).
3. Set the time zone on the **first** computer to be UTC.
4. Look at the current date and time in UTC. If it's just a couple minutes away from midnight, you might want to wait about 23 hours because you'll need a few minutes at the end of a UTC day for the next steps. 
5. Open `website/common/script/content/constants.js` in an editor and find the place where `2019-11-02` appears - that's the end date for the Fall 2019 Grand Gala. Change that to **tomorrow's** date (in UTC time). For example, if the current day in the UTC time zone is 2019-11-08 then change `2019-11-02` to `2019-11-09`. The output of `git diff` should look something like this:
```
diff --git a/website/common/script/content/constants.js b/website/common/script/content/constants.js
index 1b210c5749..2298319584 100644
--- a/website/common/script/content/constants.js
+++ b/website/common/script/content/constants.js
@@ -37,7 +37,7 @@ export const EVENTS = {
   summer2019: { start: '2019-06-18', end: '2019-08-02' },
-  fall2019:   { start: '2019-09-24', end: '2019-11-02' },
+  fall2019:   { start: '2019-09-24', end: '2019-11-09' },
 };
```
6. Start the local install's Habitica webserver -- i.e., use `npm start` and `npm run client:dev` as normal.
7. Find your **local network** IP address for that computer (it will probably be in one of these ranges: 10.0.0.0-10.255.255.255, 172.16.0.0-172.31.255.255, 192.168.0.0-192.168.255.255).
8. Go to a **second** computer on the same network. You do not need to install Habitica locally there.
9. Set the time zone of that computer to be in a region that is **behind** UTC. That's important. It must not be set to UTC or any time zone ahead of UTC. For example, the America/New_York zone is appropriate.
10. Close your browser on that **second** computer (close all browser windows) and reopen it. That's necessary to ensure your browser picks up the new zone.
11. Use the IP address of the **first** computer to access the Habitica webserver from the browser on the **second** computer. For example: http://192.168.0.2:8080 (the exact address will depend on your local network).
12. Create a new Habitica account there.
13. Go to User Icon > Settings and look in the Time Zone section. Confirm that the time zone there is displayed as being behind UTC. For example, `UTC-5:00`
14. Use Fix Character Values to give yourself a few hundred gold.
15. Go to Shops > Market and look in the Equipment section. You should see the Grand Gala gear for a Warrior available for sale.
16. On the **first** computer, check that the date in UTC time is still before the end of the Grand Gala (i.e., to use the sample dates above, it must be still 2019-11-08).
17. On the **second** computer, buy one of the Grand Gala equipment pieces and confirm that the purchase did work (e.g., reload the website and check that the new item does appear in your Equipment list).
18. Wait until the date on the **first** computer reaches the end date for the Grand Gala (i.e., wait until it becomes 2019-11-09 in the UTC time zone using the sample dates above). However do not wait too long. It must still be 2019-11-08 on your **second** computer.
19. On the **second** computer, try to buy another one of the Grand Gala equipment pieces. Confirm that the purchase fails - at first it will look like it succeeded but then you'll see the "You can't buy this item" error message and when you reload the website you'll see that the item is still for saile and does not appear in your owned equipment list. See the reports above from Praxis for a description of the buggy behaviour.

Hopefully I've got that all correct. :-/ Post here if you have any questions.

**Comment by Alys** [comment]
So to summarise the bug: 

- Habitica's code specifies the end date of a Grand Gala (that's the `2019-11-02` date in `website/common/script/content/constants.js` that I mentioned above).
- If your own computer's date is before that end date, the website will show the Grand Gala equipment as being for sale, and will let you buy it. Whether the purchase is actually successful depends on the next two points.
- If Habitica's server's date is also before the end date, your purchase will succeed.
- If Habitica's server's date is after the end date, your purchase will fail, even though at first it seems to succeed.

FYI Habitica's production server uses the UTC time zone.

**Comment by Alys** [comment]
~From a VERY quick and dirty test, I _think_ we might be able to fix this bug by changing this code:~

Habitica's staff have approved this fix:

https://github.com/HabitRPG/habitica/blob/99599953f55766fb447707594fe1c66a78d9e89d/website/common/script/content/gear/index.js#L65-L66

so that `moment().isBefore(item.event.end)` becomes `moment().isBefore(moment.utc(item.event.end))`

EDIT: we might want to adjust the `isAfter` code in the same way for consistency although that's not directly related to this bug.
EDIT to the edit: If we don't handle the start-of-Gala case correctly, we might get the same bug as this one but for people in time zones ahead of UTC. For example, with me at UTC+10, the start date of a Grand Gala will arrive before the server thinks the Gala is supposed to start. If the website shows me the equipment too early and lets me try to buy them, I think I'd get the same failure as Praxis did but at the beginning of the Gala (not a huge problem since I could just re-buy the gear several hours later, but it would still be good to avoid the bug reports).

Reference:
https://momentjs.com/docs/#/parsing/
> moment(...) is local mode. Ambiguous input (without offset) is assumed to be local time. Unambiguous input (with offset) is adjusted to local 
> moment.utc(...) is utc mode. Ambiguous input is assumed to be UTC. Unambiguous input is adjusted to UTC.

However I've done just one test on the website using the scenario from my points 18 and 19 in my comment above, and just after that the time clicked over to be too late for that scenario to be used again, so I wasn't able to replicate the successful test today. (I can't replicate tomorrow either; I won't have two PCs at my disposal in the right time frame, and the day after that is a work day.)

If anyone works on that fix, it should ideally be tested more thoroughly on the browser, on PCs set to a variety of zones before, at, and after UTC, and also tested through the API.

**Comment by Alys** [comment]
I've updated my previous comment with a couple of notes:

**Comment by Alys** [comment]
[so sorry for the email spam, I hit submit accidentally]

I've updated my previous comment with a couple of notes:

"EDIT: we might want to adjust the `isAfter` code in the same way for consistency although that's not directly related to this bug.

"EDIT to the edit: I we don't handle the start-of-Gala case correctly, we might get the same bug as this one but for people in time zones ahead of UTC. For example, with me at UTC+10, the start date of a Grand Gala will arrive before the server thinks the Gala is supposed to start. If the website shows me the equipment too early and lets me try to buy them, I think I'd get the same failure as Praxis did but at the beginning of the Gala (not a huge problem since I could just re-buy the gear several hours later, but it would still be good to avoid the bug reports)."

**Comment by Alys** [comment]
Just to confirm, this is still happening, and since it happens for limited-time magic hatching potions as well as for seasonal gear, I've updated the title. 

@bgmary (512cab82-38b9-46cf-b00e-8fa4efbcb575) reported:

"Whenever I try to use one of my thunderstorm potions, it works and hatches the pet, but if I try to feed the pet, I get an error that the pet doesn't exist, that I don't have the potion, and suddenly all my thunderstorm potions are gone and I'm reimbursed in gems. When I try to buy them back, it works, but I simultaneously get an error message that they're not available for purchase. Have screenshots of myself owning the potions, and as you will be able to see in the logs, I clearly don't now despite not having used them. I get that it's now Dec 1st, but seems unfair to sell them to me then take them back."

**Comment by hathschi** [comment]
I would like to work on this issue, if it is still available.

**Comment by CuriousMagpie** [comment]
@hathschi Sure thing--thanks!

**Comment by Tressley** [comment]
Closing as we believe this bug was addressed in our newest changes to how content is handled. If the problem resurfaces, we will open a new issue.
