### ISSUE TITLE
[API v3] Challenge and deleting challenge bugs

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7272]
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

When creating a new challenge

1) You can choose from all the guilds for the challenge to be held in, instead of just the ones you are part of

2) You can't add multiple tasks at once (the button does nothing)

~~3) You can't remove tasks or leave when leaving, it will just pop up a new bubble with options remove tasks/keep them/cancel, the first 2 does nothing. Only cancel works.~~

4) When deleting the challenge, you won't get the gems back

5) After deleting a challenge, the tasks remain and the megaphone icon is not broken.

**Comment by paglias** [comment]
3. is fixed

**Comment by paglias** [comment]
Number 3 is fixed

**Comment by Memry** [comment]
#2 doesn't work in live data either

And I cannot close my challenge.  It shows no participants.

**Comment by TheHollidayInn** [comment]
I will take these.

**Comment by paglias** [comment]
@Kryzowsky 4 works for me. It's possible that you tried to delete and old challenge in which cause you wouldn't get refunded because the migration had a bug that meant all prizes where set to 0

**Comment by paglias** [comment]
This should be fixed now, reopen if it isn't

**Comment by Kryzowsky** [comment]
Deleting a challenge still doesn't give gems back (at least not immediately, or after sync)

**Comment by paglias** [comment]
Did you try with a new challenge? Challenges from the old site have a bug
that caused the prize to be set to 0
Il 17 mag 2016 8:27 AM, "Kryzowsky" notifications@github.com ha scritto:

**Comment by Kryzowsky** [comment]
Yes, I did try with a new one I have just created. It even showed the gem prize in the Tavern unlike all the others.

**Comment by Alys** [comment]
Confirmed that when I create a new challenge with a gem prize and then delete the challenge, I do not get the gems back, even after a sync or reload. That was tested with a new challenge created on the test site.

If I create a new challenge with a prize and declare myself the winner, I do get the gems back after syncing.

**Comment by TheHollidayInn** [comment]
Hmm. I didn't make any changes to fix this. We couldn't confirm the issue, but it seems it is continuing. I'll try to replicate locally with the updates.

**Comment by Alys** [comment]
from server/models/challenge.js:

```
  // Refund the leader if the challenge is closed and the group not the tavern
  if (challenge.group !== TAVERN_ID && brokenReason === 'CHALLENGE_DELETED') {
    await User.update({_id: challenge.leader}, {$inc: {balance: challenge.prize / 4}}).exec();
  }
```

That exemption for the Tavern is the problem. @Kryzowsky and I were testing with Tavern challenges. I've just tested with a non-Tavern challenge and deleting it causes gems to be returned correctly.

I don't believe that exemption should be there, even if that's current behaviour on the production site. Sometimes you do legitimately need to delete a challenge. Challenge creators who abuse the system by creating then deleting a challenge are probably rare - they don't get much out of it.

**Comment by Alys** [comment]
> 1) You can choose from all the guilds for the challenge to be held in...

Looks fixed.

> 2) You can't add multiple tasks at once (the button does nothing)

That same bug exists in production so we don't need to fix it in API v3 yet. It will be fixed in future in https://github.com/HabitRPG/habitrpg/issues/6723

> 5) After deleting a challenge, the tasks remain and the megaphone icon is not broken.

I can't replicate that in one test. However it's well known on the production site (a timeout error, I believe) so it's not impossible the same thing is happening with v3. We can work on it in future in https://github.com/HabitRPG/habitrpg/issues/2763

**Comment by paglias** [comment]
@Alys that exception was in v2, I can remove it if you want

**Comment by Alys** [comment]
Let's leave it for now, we can remove it later. I'm closing this but adding it to my list of things to look at after go-live. Sorry, paglias, I should have noticed that sooner. :(
