### ISSUE TITLE
[API v3] Payments Bugs

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7311]
- The first time I purchased gems via Stripe, the entire page went entirely blank and had to be reloaded. On a refresh, all was normal and the gems had been awarded. I was unable to replicate this, so it may have been a fluke.
- Attempting to cancel a 3-month recurring subscription resulted in the error message: {"success":false,"error":"NotAuthorized","message":"Missing authentication parameters."} and I was unable to cancel the subscription. This has been consistent.
- While having a subscription purchased with Stripe, I was successfully able to buy gems via Stripe, but attempting to buy them via Paypal resulted in the message {"success":false,"error":"NotAuthorized","message":"Missing authentication parameters."} again. Amazon successfully opened its window, but then they directed me to a popup that said, "We're sorry!
  An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly." Clicking on "Show details" resulted in the following: "Error Summary
  400 Bad Request
  The domain on which you are using the JavaScript SDK has not been whitelisted for your application. Please add your website domain in the 'Allowed JavaScript Origins' section under 'Web Settings' on the Amazon Seller Central App Console for Login with Amazon.
  Request Details
  client_id=amzn1.application-oa2-client.68ed9e6904ef438fbc1bf86bf494056e
  redirect_uri=https%3A%2F%2Fapi-cdn.amazon.com%2Fsdk%2F2016-03-08-1t71b9cw%2Ftopic.html%3Furi%3Dhttps%253A%252F%252Fv3.habitica.com%252F%26proxy%3Damazon-proxy-https-api_cdn_amazon_com%26topic%3DoqifqwkI4z6jsF8w%26version%3D1
  response_type=token
  scope=payments%3Awidget
  language=
  ui_locales=
  sandbox=true"

**Comment by quin-jay** [comment]
Possibly related: Every pageload creates these errors in the console. I can't think of any other reason besides payments that Habitica would need to load anything from Amazon

```
payments-sandbox.amazon.com/gp/cba/uedata/190-6970067-9945301?ld&v=28&id=MK…=0&hob=1&hoe=2&ld=165&t=1463433837299&ctb=1&csmtags=nonredirect|noAmznJQ:1 GET https://payments-sandbox.amazon.com/gp/cba/uedata/190-6970067-9945301?ld&v=…rc=0&hob=1&hoe=2&ld=165&t=1463433837299&ctb=1&csmtags=nonredirect|noAmznJQ net::ERR_BLOCKED_BY_CLIENT
fls-na.amazon.com/1/batch/1/OP/A3BXB0YN3XH17H:190-6970067-9945301:MK5P0HQ7Q…165%26t%3D1463433837299%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:166:1 GET https://fls-na.amazon.com/1/batch/1/OP/A3BXB0YN3XH17H:190-6970067-9945301:M…3D165%26t%3D1463433837299%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:166 net::ERR_BLOCKED_BY_CLIENT
```

Then again, these errors also appear in the production site, so either there's a bug that's live that's just become a problem with the v3 changes or these errors aren't related to these payment bugs.

**Comment by quin-jay** [comment]
Also: I see the same behavior when attempting to cancel a 6-month subscription. 

Also also: It looks like in v3 the Subscription page is supposed to tell you how long it'll be before your subscription renews, but it's factored wrong -- It tells me how long it's been since I subscribed:
`[credit card icon] You have -1.00 months of extra subscription credit.`
Not strictly a payments bug, but probably an easy fix if you're going to be in those files anyway. (side note: we may want to rephrase that string too because it took me a second to figure out what it was supposed to be telling me)

**Comment by Alys** [comment]
@lynnyliz That `-1.00 months` message is likely to be a thing in your account. What's your User ID?

**Comment by Alys** [comment]
@lynnyliz never mind about the uuid, I found it. :)  That was a problem in your account - your subscription data had a negative extra months value. I've fixed it in the test database. Please check the subscription page again.

FYI, all the negative credit amounts have already been fixed in the production database, so that won't come back for your account after the next migration.

**Comment by quin-jay** [comment]
Oh hey, now both versions of my account look the same. Thanks, @Alys! :D

This gave me an idea for a new feature I could maybe start working on eventually -- Showing what date you subscribed and when you'll be re-billed! It was super handy when I thought that's what the error was :stuck_out_tongue_winking_eye:

**Comment by lemoness** [comment]
Just chiming in to say that would be a great feature!

**Comment by paglias** [comment]
Errors should be fixed now!

**Comment by lemoness** [comment]
Unfortunately, still getting the "{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}" when I try to purchase gems through Paypal.

When you try to subscribe via Paypal, it all seems to work normally, until the final step, when it throws the error message "{"err":"Cannot read property 'key' of undefined"}" 

But it looks like it might not be using v3.habitica? The address is "https://habitica.com/paypal/subscribe/success?token=EC-7GW18092AA9748426"

**Comment by paglias** [comment]
Fixed, though it won't work on v3.habitica.com
