### ISSUE TITLE
Chrome Chat Client does not allow you to post for the Newbies Guild after API v3 upgrade

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7416]
_This has been reported here at the request of @Alys as it may be linked to other broader issues_
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description

The chat client for the [Newbies Guild](https://habitica.com/#/options/groups/guilds/5481ccf3-5d2d-48a9-a871-70a7380cee5a) I am able to see posts but unable to respond through them through the client. (See Image)

![chatwindownotshowingwithtavernshowing](https://cloud.githubusercontent.com/assets/14116069/15453546/2ec57fa4-205d-11e6-8fa2-5135c642eb11.png)

I just joined the [The Scholars](https://habitica.com/#/options/groups/guilds/82fe50b1-4fa5-4e94-8114-aa66516c0d9d) and it appears to have the same results, where the chat appears, but not the ability to reply or heading text for the guild.

I am able to see correctly though:
- All my other guilds (My biggest is 293 _seems I don't like large crowds_)
- Party 
- Tavern
### Other things to note
- Avatars are not appearing. Just getting continuous fetching symbols This is new. Just not sure if due to the traffic of everyone logging on at once from the update.
- Emjois still not working (Wasn't working before API v3 so not working now)

**Comment by Alys** [comment]
Ha, this IS relevant to us. The problem with the avatars not appearing is in our code so this was a useful thing for us to know about.

I wonder -- blind guesswork here -- if once we fix the avatar bug, maybe the rest of the chat client will start working on the big guilds. Perhaps it's just overloaded with attempts to get the avatars.

**Comment by Alys** [comment]
GitHub repo for the client: https://github.com/Horacious/HabitRPG-Chat-Extension

Extension page: https://chrome.google.com/webstore/detail/habitica-chat-client/hidkdfgonpoaiannijofifhjidbnilbb

**Comment by crookedneighbor** [comment]
I have a PR out for the emojis/markdown issue: https://github.com/Horacious/HabitRPG-Chat-Extension/pull/40

The only thing on our side is the v2 avatar export route, which the chat client uses. Thanks for reporting this!

**Comment by paglias** [comment]
Avatars not displaying should be fixed

**Comment by Alys** [comment]
@cTheDragons Are you still unable to post to the Newbies guild or the Scholars guild using this extension?

**Comment by cTheDragons** [comment]
Yes woke up this morning and still no change.

(Including Avatars)

**Comment by Alys** [comment]
@cTheDragons So you're still not seeing avatars in the chat client? Even after a reload?

**Comment by cTheDragons** [comment]
ohh... For most, but I just noticed my Avatar is coming up... and most of my Party. Just not for the Tavern or Newbies.

**Comment by cTheDragons** [comment]
Ok a few more moments have past and the some of the Avatars in Newbies and Tavern are now appearing. Also in the smaller guilds too.

**Comment by cTheDragons** [comment]
Hi I'm still unable to post to the Newbies Guild. (Despite the Avatars has been fixed). Has this been closed as it will now been fixed under [the issue listed in the Chat Client](https://github.com/Horacious/HabitRPG-Chat-Extension/issues/42)?

**Comment by crookedneighbor** [comment]
Sorry, didn't realize it was still not working. Will look into this. 

HabitRPG, Inc. has officially taken over maintaining the chat client, so I've ported the chat issue here: https://github.com/HabitRPG/habitica-chat-extension/issues/5

**Comment by crookedneighbor** [comment]
@cTheDragons I've just fixed it and published a new version of the chat extension. v1.4.0

**Comment by cTheDragons** [comment]
Hi I have downloaded 1.4.0 and it does not work. It does not come up with your groups tab so you can select which chat windows. Other than the icon at the top it does nothing! Could we revert back the old version on the Chrome store so I can at least download the buggy version.

Thanks

**Comment by crookedneighbor** [comment]
@cTheDragons Are you sure you don't just need to re-link your account?

**Comment by cTheDragons** [comment]
Ah! `Facepalm` Forgot to check the machine between the keyboard and the screen. Can see the Newbies guild now. Were we meant to lose the Avatars though?

**Comment by crookedneighbor** [comment]
Are they lost or just taking a while to populate?

**Comment by crookedneighbor** [comment]
Hmmm... I wonder if Horacious updated the chrome extension without updating the repo. Could you open an issue https://github.com/HabitRPG/habitica-chat-extension/issues

**Comment by cTheDragons** [comment]
[Done](https://github.com/HabitRPG/habitica-chat-extension/issues/8)

Thank you for your hard work!
