### ISSUE TITLE
Tasks with broken challenge links - unable to "keep" them and getting an error message

### ISSUE THREAD

**Issue by Definitia** [HabitRPG/habitica#7587]
UUID: fbcc1ddd-a6ef-499a-ae30-fa817b000438
Browser: Mozilla Firefox 46.0.1
OS: Windows 7

Whenever there is a task with a broken challenge link (i.e. the challenge is already completed or deleted), upon clicking the broken challenge icon on the task there is an option to either keep the challenge tasks (thus unlinking them from challenge so they are open to editing etc) or remove them. Whenever I try to select "keep", the tasks remain linked to the challenge and 3 error messages display - as seen in the attached screenshot. So basically, I cannot make them "my" tasks. The option for removing the challenge tasks altogether works normally.
![habitica_bug2](https://cloud.githubusercontent.com/assets/19697752/15728073/a53e3ed2-285a-11e6-8d7e-c1819afbe245.jpg)

**Comment by Definitia** [comment]
I believe a similar issue submitted earlier today might be connected: https://github.com/HabitRPG/habitrpg/issues/7569

**Comment by paglias** [comment]
@Definitia thanks for the report! Actually this is caused by a bug in our ORM (https://github.com/Automattic/mongoose/issues/4182) but it should be fixed fairly quickly!

**Comment by crookedneighbor** [comment]
This can be closed when mongoose@4.4.20 or higher is released.

**Comment by paglias** [comment]
This should be fixed now, mongoose@4.4.20 was released 12 hours ago

**Comment by Alys** [comment]
This is still happening on the habitica.com site and staging site, with the error notifications appear just as in the screenshot above and this in the console:

POST https://habitica.com/api/v3/tasks/unlink-all/ae7118bf-760d-411f-979c-1d417164d2b1?keep=keep-all&userV=3799 400 (Bad Request)

**Comment by paglias** [comment]
Confirmed :( I've asked to reopen the Mongoose issue here https://github.com/Automattic/mongoose/issues/4182

**Comment by paglias** [comment]
Fixed
