### ISSUE TITLE
Missing Rewards

### ISSUE THREAD

**Issue by fsiah2** [HabitRPG/habitica#778]
When the potential mem-leak fix was released today I lost the list for standard rewards, such as armor and weapons.  I do not use custom rewards, so I do not know if that was affected.  When I switched to the beta server the list reappeared.  After the server reboot today my rewards list reappeared.

**Comment by lefnire** [comment]
I think this is fixed now. The production server was having some chef-client permission & disk usage issues, we got that solved, rebooted - and it sounds like that fixed your error. We should be in the clear now, re-open if this comes back.

**Comment by guifes** [comment]
I still can't see my default rewards. Only the custom ones. Although I can see them on my Android app.

**Comment by SabreCat** [comment]
@guifes: What level are you? Default rewards don't unlock until level 2 or 3, I believe.

**Comment by guifes** [comment]
I'm at level 1, and I know now that I'm not supposed to see the default rewards yet. But I can see them in the Android mobile app, maybe you guys will want to check that out. I even bought a helmet and I'm still level 1.

**Comment by SabreCat** [comment]
@guifes, can you open a ticket over at [habitrpg-mobile](https://github.com/HabitRPG/habitrpg-mobile/issues)? I think this is a known issue, but I don't see a ticket out for tracking it.

**Comment by guifes** [comment]
Done!
