### ISSUE TITLE
New Pet Layout lost my pet, says I have 6/90 pets founds, but only displays one (not my original pet thats gone missing)

### ISSUE THREAD

**Issue by AngeloAdam** [HabitRPG/habitica#827]
My original pet was veteran wolf. It doesnt appear in the stable after the new layout implemented. 

It says I have 6/90 found, but only displays one flying pig.

**Comment by heyimzsa** [comment]
The same thing has happen to me. I had two pandas, a dragon, and a lion and only one panda shows up. 
—

**Comment by Shaners** [comment]
Not a real fix but try scrolling all the way to the bottom of that window to see the horizontal scroll bar. Wouldn't help with veteran I don't believe.

**Comment by lefnire** [comment]
Ok, added Veteran Wolf back in - very rare pet right now (aka, you can't even earn it anymore!), so I placed it at the bottom of the modal. I also fixed a tooltip bug that _may_ have been causing the number / shown disconnect, can y'all experiencing the issue try again?

Random aside, check out https://github.com/lefnire/habitrpg/issues/828 for a real layout discussion

**Comment by lefnire** [comment]
and if you're still having issues, can you post your user id?

**Comment by AngeloAdam** [comment]
i still see 6/90 and now only two pets in the stable (flying pig, and veteran wolf).

worth noting is that prior to the new pet layout, i had multiple instances/copies of the white flying pig being displayed in the modal. this might account for why tooltip says 6/90. but only shows one pet in the stable.

**Comment by lefnire** [comment]
aahhhh, that is indeed the problem. What I need to do is add a "5x" bottom corner of the flying pig or something. The actual problem is that the app is supposed to prevent creating the same pet multiple times, it throws a pop-up error "you already have that pet try a different combo". Somehow your account got past it. @lemoness may take interest, we had a discussion - she was in favor of multiple pets, I was against them (since they serve no purpose). Though there may possibly be pet gifting amongst your party in the future? That might make duplicates worth it (in which case, sorry @lemoness for the push back). We'll cross that road later, but for now I'm marking this as minor

**Comment by bobbyroberts99** [comment]
I'm having a similar problem. My avatar drop down (the modal?) says 5/90 found, stable only shows 2. I have hatched five pets.

I also seem to need to reload the page after hatching a pet before the avatar reports the recently hatched egg as found. This is true on mac safari and iPad safari. Haven't yet tested it in Firefox or Chrome yet. Other than this problem, beta.habitrpg is mostly running without problem (sometimes I have to perform an action twice for it to take) across 3 platforms (including iPhone safari). 

user: bobbyroberts99

**Comment by fishstix43** [comment]
I have a similar problem.  I only have one pet, but the dropdown shows that I have 4. I have only hatched one, but I did have the same thing as come2gether where before the new layout where multiple copies of my one pet were showing up.  Just wanted to throw it out there that this does happen without losing any pets in my case, in case it helps diagnose the problem or whatever when you guys have time to look at it.

**Comment by lemoness** [comment]
Funny, I seem to have actually GAINED two pets, at least according to my status message. Browsing the stables actually does not show any added pets, though, although the layout makes it a little difficult to tell.

**Comment by BHGobuchul** [comment]
Similar problem, well not a massive one. Says I've unlocked 4 pets when I know (and it displays) only the 3 pets I have unlocked.

**Comment by lefnire** [comment]
Is this still a problem for anyone? Big pet fixes went out recently
potentially fixing these issues

**Comment by BHGobuchul** [comment]
I just checked my stable, still says I have 4 when I know (and can see) I only have 3 hatched.

**Comment by tschollie** [comment]
I have the same problem as BHGobuchul: 12 hatched pets, but the counter says 14/90.
Everything was okay for the first 10 pets, only the last two were counted twice.

Also from time to time a dropped egg doesn't show up in the inventory.

**Comment by scroll** [comment]
For me this is still an issue from the time the new layout was introduced. The pet count is more than what I actually have.

**Comment by baconsaur** [comment]
Similar problem, but I'm not missing any pets. All 13 that I've hatched are there, but the counter jumped up to 22 after I hatched my latest pet.

**Comment by wc8** [comment]
is this the same as #952?

**Comment by StanLindsey** [comment]
@lefnire - is it an issue of the pets being displayed in the stable & the text "6/90 unlocked" are being pulled from different areas/at different times and becoming out of sync?

**Comment by lefnire** [comment]
no, this looks like one of those `model.push` / `model.unshift` bugs causing duplicates again. one of those Derby 0.5 bits. What's happening is they hatch the pet, `model.push('_user.items.pets',newPet)` on a slow connection or server high-RAM, and it causes duplicate pushes. They can't tell the difference because the interface only shows one of any pet-combo

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
