### ISSUE TITLE
Docker - ELIFECYCLE error

### ISSUE THREAD

**Issue by Caryyon** [HabitRPG/habitica#8554]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: f146bebb-2e95-4dfb-8bea-5621a3bbec4a
  * OS: Docker

### Description
Following the Docker instructions on the habitica wiki I'm getting an error when running the command: ```docker-compose up -d``` It in turn does not start up either containers.

#### Console Errors
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moment-recur@1.0.5 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moment-recur@1.0.5 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the moment-recur package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs moment-recur
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls moment-recur
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-03-10T20_26_25_177Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by TheHollidayInn** [comment]
We have just merged in or are about to merge in a forked version of moment-recur that should fix this issue. @SabreCat

**Comment by Caryyon** [comment]
@TheHollidayInn has this been merged? I've fetched the new version and i'm still getting the same error.

**Comment by paglias** [comment]
@Caryyon it should be merged by now, can you try again?

**Comment by Caryyon** [comment]
I'm still seeing the same error. I'm looking into it on my side as well.

**Comment by paglias** [comment]
@Caryyon the problem is that we're not using anymore the code that cause that error. Can you try to reinstall from scratch making sure the repository is up to date?

**Comment by jcgruenhage** [comment]
I have the same issue, but only with NODE_ENV set to production. With that set to developement, it works.

**Comment by BennyHarv3** [comment]
I think this issue is obsolete? I just ran all the Docker container instructions in the [wiki](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Docker) and didn't encounter this. Did encounter #8909 and #8910, though, but I fixed them and opened a PR for them.

**Comment by SabreCat** [comment]
@BennyHarv3 Thanks for pointing that out! I'll close this issue, but of course we can reopen it if anyone runs into trouble again.
