### ISSUE TITLE
Current unstableness, the "Offline - Reconnect" issue

### ISSUE THREAD

**Issue by mawson94** [HabitRPG/habitica#91]
I just found out about this site/ made an account today and I love the idea so far but:
After logging out it seems to be impossible to log back in. 
The two main problems are:
1.) Log in button is greyed out (seen an issue post for this already) and the word "disconnected" appears next to my username in red.
2.) The message "offline - reconnect" appears at the top of the page and upon clicking "reconnect" the word "offline" is shown briefly until returning to the original message

I signed up using my email and not Facebook if that makes a difference?

**Comment by Mnnwbdd** [comment]
I had this exact same experience.

**Comment by lefnire** [comment]
@mawson94 a lot of people are chiming in with this issue, I'm going to direct everyone here as the main discussion. First off, the login button being greyed out is a different issue (#89). 

Offline - Reconnect. The server is experiencing [this](https://github.com/lefnire/habitrpg/issues/80) (unknown cause, diagnosing) which is causing [this](https://github.com/lefnire/habitrpg/issues/84). Seems to be highly exacerbated by load balancing issues, because it was quite rare up until now (I had the pleasure of being Reddted this morning). I've upped the dynos, but that's not seeming to fully fix it. I'm going to be working on this all day. Any JavaScript developers out there?

**Comment by lefnire** [comment]
@bsideballer said

> I also noticed that a TON of XHR requests are being sent on page load/task submit when the page loads correctly (read: hundreds of requests). These issues could be related?

I'll keep this in my back pocket as I'm diagnosing the issues. Heroku doesn't support websockets, so Derby is falling back on XHR-polling. I thought that would actually scale _better_ since it doesn't keep open connections (memory pooling), but maybe not - I'm going to be trying to setup an AWS today

**Comment by lefnire** [comment]
I'm working on a static page for new visitors right no, that should reduce #80

**Comment by racuna** [comment]
Something like your video on kickstarter as a tour for visitors (hosted in youtube) would be nice.

**Comment by lefnire** [comment]
brilliant, that'll keep them occupied too :)

**Comment by lefnire** [comment]
Found it. I need to migrate to a different PaaS.

> 1. Racer is not multi-process, but this is what Joseph is going to be dedicated to when he starts soon. Using multiple processes is not going to work correctly in lots of ways right now. We should have something workable in a couple of months.
> 2. We just switched to XHR-polling for everything, because we were running into some issues with proxying websockets through node-http-proxy. Websockets should have lower overhead and be able to scale up to more active connections, but in practice it is pretty buggy still.

**Comment by lefnire** [comment]
I'm currently testing app fog, if that fails I'll likely self-host on aws. i'll check out dotcloud too

**Comment by ghost** [comment]
Go with app fog, I have heard nothing but good things about them

**Comment by BrianTolman** [comment]
Set up a aws load balancer and then then put your db on seperate db server then expand the app servers behind it.  Problem will solve itself and then you can add/subtract app servers based upon load.

**Comment by martinclavell** [comment]
im agree with @Neohuman u should use AppFog, its pretty nice

**Comment by lefnire** [comment]
can't get it to launch, getting some funky errors. i'll keep trying

**Comment by eduardocruz** [comment]
Not sure if this can help in any way, but here it goes ... https://github.com/lloyd/node-toobusy

**Comment by JamPol** [comment]
If you just changed something, it worked. HabitRPG just started working really well for me!

**Comment by sigboe** [comment]
JamPol, not feeling the same. Erratic offline/reconnecting. Haven't tried clicking any + or - buttons as I need to do something good first haha. Workout session in a few hours so gonna try then xD

**Comment by lefnire** [comment]
still working b/w appfog & aws. nothing fixed, stayed up all night. hang in
there guys

**Comment by SamPearson** [comment]
I appreciate the hard work and can't wait to continue using the site.

**Comment by lefnire** [comment]
we don't happen to have any baller sysadmins on this thread do we?

**Comment by JamPol** [comment]
Appreciate the hard work, but unfortunately I'm not a baller sysadmin. Best advice is to post issue on http://www.reddit.com/r/programming/ or  http://www.reddit.com/r/gamedev/ they're both filled with hundreds of knowledgeable folk, even at this very moment they're both 200+ users online. Someone should be able to help.

**Comment by JamPol** [comment]
Just wanted to let you know it flip-flopped. Right now it's displaying all the info I entered this morning when I posted that it was working really well and was running smoothly. Then it reverted to my old list for a while which didn't work very well, now it's back to smooth sailing.

Pure speculation, but maybe there's two copies fighting over the server?

**Comment by dmuth** [comment]
I don't know if I'm a baller sysadmin, but I have a fair bit of sysadmin experience and an AWS background. I also do a lot of backend node.js stuff for a living.  Feel free to shoot me a private email if you'd like to pick my brain.

**Comment by lefnire** [comment]
we're almost up on liquid web (@alanthing helping out, he's a ninja!) - more soon

**Comment by lefnire** [comment]
ok! we are migrated, and should be mostly in the clear. there are still some issues to pan out, follow #80 for the biggest bug specifically. 

My suggestion for now - you're good to play, but if you see the "offline" message, refresh before making changes. This will be fixed #80

**Comment by JamPol** [comment]
Thanks for the hard work, so psyched now.

**Comment by eduardocruz** [comment]
FYI -> "Internal Server Error" for the last two hours.

**Comment by SamPearson** [comment]
Still getting "offline - reconnect" frequently; have to make changes and refresh multiple times to get them to stick.

**Comment by theogeer** [comment]
I'm still getting offline - reconnect every 3-5 minutes as well

**Comment by lefnire** [comment]
Yep, still there. Better than before (trust me), but still there. It's #80. Any node devs out there check it out if you get the chance, that's where I'll be spending my day.

**Comment by yeahilift** [comment]
do you have any estimate of the time until it's fixed? i know a lot of my students/friends are anxious to try this out

**Comment by lefnire** [comment]
no ETA yet unfortunately, I keep thinking it's just around the corner. I have a [lead on the fix](https://github.com/lefnire/habitrpg/issues/80#issuecomment-12428635), I'm going to try that out - if it works, a few hours. if not, next rabbit hole :) Here's the thing about Derby. unfortunately it's very difficult to test this issue locally, trying to devise a way...

**Comment by hrj** [comment]
The later you fix, the more points you will get
:wink:

**Comment by lefnire** [comment]
@hrj ooh i need that laugh :D

**Comment by lefnire** [comment]
Status:
Talked to Brian (Racer dev) about #80 (the king error), he said just up the timeout. I followed [this advice](https://github.com/codeparty/derby/issues/152#issuecomment-12420804) to up the amount [here](https://github.com/lefnire/habitrpg/commit/76ae83b2f08e3f7ee3f463a06b4590f63ef00d1e). Still kept getting some timeout errors on 1000ms (even though I set it to 7000ms), but less common (good). Maybe that configuration isn't respected somewhere. In the end, we still need a `model.update` operation to get past this database-DDoSing (locking), as I pointed out [here](https://github.com/lefnire/habitrpg/issues/80#issuecomment-12435499), I think that will be the ultimate fix. 

Luckily, we're crashing a lot less frequently. Stay tuned.

**Comment by lefnire** [comment]
also, special thanks to @Andrew565 - he's been helping a lot, and learned the codebase _fast_. With any luck we should be stable today. If there are any other JavaScript devs that want to help, please jump on #80

**Comment by lefnire** [comment]
alright! how we doing? I think we fixed it guys

**Comment by theogeer** [comment]
It's been doing pretty good for me the last couple hours. I'm super excited

**Comment by ghost** [comment]
Registration still doesn't work. Says invalid login & username not registered.

**Comment by lefnire** [comment]
@Neohuman is it #89 the greyed out button?

**Comment by ghost** [comment]
Yes it is

**Comment by lefnire** [comment]
kk, i'm gonna close this ticket but keep a keen eye on it. will re-open if it comes back. i'll start working on #89
