### ISSUE TITLE
rejecting a guild invitation failed repeatedly with an inappropriate error in our logs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9808]
I haven't fully investigated this but it looks like there might be a problem with rejecting guild invitations.

In the Report a Bug guild, KrispyGamer (3518183e-c25e-4729-9057-5bd95732d7e8) wrote:

"... my notifications have been a bit buggy. I got invited to a guild by someone and no matter how many times I rejected it, the notification would go away. Now it has finally disappeared but I am not getting any notifications since I was invited to a party (notified by email) but I can not do anything to actually join it or anything"

The error below appeared in Loggly at least twice for the same guild:
```
NotAuthorized: Can't join a group you're not invited to.
.... 
method:POST
originalUrl:/api/v3/groups/e184b286-b369-46c9-ab55-054c3368af33/reject-invite
```

That's actually a **public** guild and the player was trying to **reject** the invitation, so the error "Can't join a group you're not invited to" shouldn't have appeared.

----

The problem with the party invitation failing was probably unrelated and due to the party having been deleted (i.e., probably doesn't indicate a bug and can be ignored unless we get more reports). The error below is for a group ID for a party that no longer exists:
``` 
GET
originalUrl:/api/v3/groups/party
timestamp:2018-01-14T06:13:19.676Z
fullError:{ name: "VersionError", message: "No matching document found for id "3518183e-c25e-4729-9057-5bd95732d7e8"" }
```

**Comment by TheHollidayInn** [comment]
I've confirmed this happens because the notification isn't remove from the menu when rejecting. @paglias Is this fixed in your new PR?

**Comment by paglias** [comment]
this is actually still happening in my PR but it shouldn't, working on it
